# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LivekitProtocolEx.BackupCodecPolicy do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :PREFER_REGRESSION
    def default() do
      :PREFER_REGRESSION
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:PREFER_REGRESSION) do
    0
  end

  def encode(:SIMULCAST) do
    1
  end

  def encode(:REGRESSION) do
    2
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :PREFER_REGRESSION
  end

  def decode(1) do
    :SIMULCAST
  end

  def decode(2) do
    :REGRESSION
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [{0, :PREFER_REGRESSION}, {1, :SIMULCAST}, {2, :REGRESSION}]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:PREFER_REGRESSION) do
      true
    end

    def has_constant?(:SIMULCAST) do
      true
    end

    def has_constant?(:REGRESSION) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
