# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LivekitProtocolEx.DataPacket.Kind do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :RELIABLE
    def default() do
      :RELIABLE
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:RELIABLE) do
    0
  end

  def encode(:LOSSY) do
    1
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :RELIABLE
  end

  def decode(1) do
    :LOSSY
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [{0, :RELIABLE}, {1, :LOSSY}]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:RELIABLE) do
      true
    end

    def has_constant?(:LOSSY) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
