# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LivekitProtocolEx.EncryptedPacketPayload do
  @moduledoc false
  if function_exported?(Protox, :check_generator_version, 1) do
    Protox.check_generator_version(1)
  else
    raise "This code was generated with protox 2 but the runtime is using an older version of protox."
  end

  @type t :: %__MODULE__{
          value:
            {:user, LivekitProtocolEx.UserPacket.t()}
            | {:chat_message, LivekitProtocolEx.ChatMessage.t()}
            | {:rpc_request, LivekitProtocolEx.RpcRequest.t()}
            | {:rpc_ack, LivekitProtocolEx.RpcAck.t()}
            | {:rpc_response, LivekitProtocolEx.RpcResponse.t()}
            | {:stream_header, LivekitProtocolEx.DataStream.Header.t()}
            | {:stream_chunk, LivekitProtocolEx.DataStream.Chunk.t()}
            | {:stream_trailer, LivekitProtocolEx.DataStream.Trailer.t()}
            | nil,
          __uf__: [{non_neg_integer(), Protox.Types.tag(), binary()}]
        }
  defstruct value: nil, __uf__: []

  (
    (
      @spec encode(t()) :: {:ok, iodata(), non_neg_integer()} | {:error, any()}
      def encode(msg) do
        msg |> encode!() |> Tuple.insert_at(0, :ok)
      rescue
        e in [Protox.EncodingError, Protox.RequiredFieldsError] -> {:error, e}
      end

      @spec encode!(t()) :: {iodata(), non_neg_integer()} | no_return()
      def encode!(msg) do
        {_acc = [], _acc_size = 0} |> encode_value(msg) |> encode_unknown_fields(msg)
      end
    )

    defp encode_value({acc, acc_size}, msg) do
      case msg.value do
        nil ->
          {acc, acc_size}

        {:stream_trailer, child_field_value} ->
          {value_bytes, value_bytes_size} = Protox.Encode.encode_message(child_field_value)
          {["J", value_bytes | acc], acc_size + 1 + value_bytes_size}

        {:stream_chunk, child_field_value} ->
          {value_bytes, value_bytes_size} = Protox.Encode.encode_message(child_field_value)
          {["B", value_bytes | acc], acc_size + 1 + value_bytes_size}

        {:stream_header, child_field_value} ->
          {value_bytes, value_bytes_size} = Protox.Encode.encode_message(child_field_value)
          {[":", value_bytes | acc], acc_size + 1 + value_bytes_size}

        {:rpc_response, child_field_value} ->
          {value_bytes, value_bytes_size} = Protox.Encode.encode_message(child_field_value)
          {["2", value_bytes | acc], acc_size + 1 + value_bytes_size}

        {:rpc_ack, child_field_value} ->
          {value_bytes, value_bytes_size} = Protox.Encode.encode_message(child_field_value)
          {["*", value_bytes | acc], acc_size + 1 + value_bytes_size}

        {:rpc_request, child_field_value} ->
          {value_bytes, value_bytes_size} = Protox.Encode.encode_message(child_field_value)
          {["\"", value_bytes | acc], acc_size + 1 + value_bytes_size}

        {:chat_message, child_field_value} ->
          {value_bytes, value_bytes_size} = Protox.Encode.encode_message(child_field_value)
          {["\x1A", value_bytes | acc], acc_size + 1 + value_bytes_size}

        {:user, child_field_value} ->
          {value_bytes, value_bytes_size} = Protox.Encode.encode_message(child_field_value)
          {["\n", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    end

    defp encode_unknown_fields({acc, acc_size}, msg) do
      Enum.reduce(msg.__uf__, {acc, acc_size}, fn {tag, wire_type, bytes}, {acc, acc_size} ->
        case wire_type do
          0 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :int32)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}

          1 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :double)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}

          2 ->
            {len_bytes, len_size} = bytes |> byte_size() |> Protox.Varint.encode()
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :packed)

            {[acc, <<key_bytes::binary, len_bytes::binary, bytes::binary>>],
             acc_size + key_size + len_size + byte_size(bytes)}

          5 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :float)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}
        end
      end)
    end
  )

  (
    (
      @spec decode(binary()) :: {:ok, t()} | {:error, any()}
      def decode(bytes) do
        {:ok, decode!(bytes)}
      rescue
        e in [Protox.DecodingError, Protox.IllegalTagError, Protox.RequiredFieldsError] ->
          {:error, e}
      end

      (
        @spec decode!(binary()) :: t() | no_return()
        def decode!(bytes) do
          parse_key_value(bytes, struct(LivekitProtocolEx.EncryptedPacketPayload))
        end
      )
    )

    (
      @spec parse_key_value(binary(), struct()) :: struct()
      defp parse_key_value(<<>>, msg) do
        msg
      end

      defp parse_key_value(bytes, msg) do
        {field, rest} =
          case bytes do
            <<_::5, 3::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 3")

            <<_::5, 4::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 4")

            <<_::5, 6::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 6")

            <<_::5, 7::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 7")

            <<0::5, _::3, _rest::binary>> ->
              raise %Protox.IllegalTagError{}

            <<9::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 case msg.value do
                   {:stream_trailer, previous_value} ->
                     {:value,
                      {:stream_trailer,
                       Protox.MergeMessage.merge(
                         previous_value,
                         LivekitProtocolEx.DataStream.Trailer.decode!(delimited)
                       )}}

                   _ ->
                     {:value,
                      {:stream_trailer, LivekitProtocolEx.DataStream.Trailer.decode!(delimited)}}
                 end
               ], rest}

            <<8::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 case msg.value do
                   {:stream_chunk, previous_value} ->
                     {:value,
                      {:stream_chunk,
                       Protox.MergeMessage.merge(
                         previous_value,
                         LivekitProtocolEx.DataStream.Chunk.decode!(delimited)
                       )}}

                   _ ->
                     {:value,
                      {:stream_chunk, LivekitProtocolEx.DataStream.Chunk.decode!(delimited)}}
                 end
               ], rest}

            <<7::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 case msg.value do
                   {:stream_header, previous_value} ->
                     {:value,
                      {:stream_header,
                       Protox.MergeMessage.merge(
                         previous_value,
                         LivekitProtocolEx.DataStream.Header.decode!(delimited)
                       )}}

                   _ ->
                     {:value,
                      {:stream_header, LivekitProtocolEx.DataStream.Header.decode!(delimited)}}
                 end
               ], rest}

            <<6::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 case msg.value do
                   {:rpc_response, previous_value} ->
                     {:value,
                      {:rpc_response,
                       Protox.MergeMessage.merge(
                         previous_value,
                         LivekitProtocolEx.RpcResponse.decode!(delimited)
                       )}}

                   _ ->
                     {:value, {:rpc_response, LivekitProtocolEx.RpcResponse.decode!(delimited)}}
                 end
               ], rest}

            <<5::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 case msg.value do
                   {:rpc_ack, previous_value} ->
                     {:value,
                      {:rpc_ack,
                       Protox.MergeMessage.merge(
                         previous_value,
                         LivekitProtocolEx.RpcAck.decode!(delimited)
                       )}}

                   _ ->
                     {:value, {:rpc_ack, LivekitProtocolEx.RpcAck.decode!(delimited)}}
                 end
               ], rest}

            <<4::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 case msg.value do
                   {:rpc_request, previous_value} ->
                     {:value,
                      {:rpc_request,
                       Protox.MergeMessage.merge(
                         previous_value,
                         LivekitProtocolEx.RpcRequest.decode!(delimited)
                       )}}

                   _ ->
                     {:value, {:rpc_request, LivekitProtocolEx.RpcRequest.decode!(delimited)}}
                 end
               ], rest}

            <<3::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 case msg.value do
                   {:chat_message, previous_value} ->
                     {:value,
                      {:chat_message,
                       Protox.MergeMessage.merge(
                         previous_value,
                         LivekitProtocolEx.ChatMessage.decode!(delimited)
                       )}}

                   _ ->
                     {:value, {:chat_message, LivekitProtocolEx.ChatMessage.decode!(delimited)}}
                 end
               ], rest}

            <<1::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 case msg.value do
                   {:user, previous_value} ->
                     {:value,
                      {:user,
                       Protox.MergeMessage.merge(
                         previous_value,
                         LivekitProtocolEx.UserPacket.decode!(delimited)
                       )}}

                   _ ->
                     {:value, {:user, LivekitProtocolEx.UserPacket.decode!(delimited)}}
                 end
               ], rest}

            <<bytes::binary>> ->
              {tag, wire_type, rest} = Protox.Decode.parse_key(bytes)
              {value, rest} = Protox.Decode.parse_unknown(tag, wire_type, rest)
              {[__uf__: msg.__uf__ ++ [value]], rest}
          end

        msg_updated = struct(msg, field)
        parse_key_value(rest, msg_updated)
      end
    )
  )

  (
    @spec unknown_fields(struct()) :: [{non_neg_integer(), Protox.Types.tag(), binary()}]
    def unknown_fields(msg) do
      msg.__uf__
    end

    @spec unknown_fields_name() :: :__uf__
    def unknown_fields_name() do
      :__uf__
    end

    @spec clear_unknown_fields(struct) :: struct
    def clear_unknown_fields(msg) do
      struct!(msg, __uf__: [])
    end
  )

  (
    @spec default(atom()) ::
            {:ok, boolean() | integer() | String.t() | float()}
            | {:error, :no_such_field | :no_default_value}
    def default(:stream_trailer) do
      {:error, :no_default_value}
    end

    def default(:stream_chunk) do
      {:error, :no_default_value}
    end

    def default(:stream_header) do
      {:error, :no_default_value}
    end

    def default(:rpc_response) do
      {:error, :no_default_value}
    end

    def default(:rpc_ack) do
      {:error, :no_default_value}
    end

    def default(:rpc_request) do
      {:error, :no_default_value}
    end

    def default(:chat_message) do
      {:error, :no_default_value}
    end

    def default(:user) do
      {:error, :no_default_value}
    end

    def default(_) do
      {:error, :no_such_field}
    end
  )

  @spec schema() :: Protox.MessageSchema.t()
  def schema() do
    %{
      __struct__: Protox.MessageSchema,
      fields: %{
        chat_message: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.OneOf, parent: :value},
          label: :optional,
          name: :chat_message,
          tag: 3,
          type: {:message, LivekitProtocolEx.ChatMessage}
        },
        rpc_ack: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.OneOf, parent: :value},
          label: :optional,
          name: :rpc_ack,
          tag: 5,
          type: {:message, LivekitProtocolEx.RpcAck}
        },
        rpc_request: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.OneOf, parent: :value},
          label: :optional,
          name: :rpc_request,
          tag: 4,
          type: {:message, LivekitProtocolEx.RpcRequest}
        },
        rpc_response: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.OneOf, parent: :value},
          label: :optional,
          name: :rpc_response,
          tag: 6,
          type: {:message, LivekitProtocolEx.RpcResponse}
        },
        stream_chunk: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.OneOf, parent: :value},
          label: :optional,
          name: :stream_chunk,
          tag: 8,
          type: {:message, LivekitProtocolEx.DataStream.Chunk}
        },
        stream_header: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.OneOf, parent: :value},
          label: :optional,
          name: :stream_header,
          tag: 7,
          type: {:message, LivekitProtocolEx.DataStream.Header}
        },
        stream_trailer: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.OneOf, parent: :value},
          label: :optional,
          name: :stream_trailer,
          tag: 9,
          type: {:message, LivekitProtocolEx.DataStream.Trailer}
        },
        user: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.OneOf, parent: :value},
          label: :optional,
          name: :user,
          tag: 1,
          type: {:message, LivekitProtocolEx.UserPacket}
        }
      },
      file_options: %{
        cc_enable_arenas: nil,
        cc_generic_services: nil,
        csharp_namespace: "LiveKit.Proto",
        deprecated: nil,
        features: nil,
        go_package: "github.com/livekit/protocol/livekit",
        java_generate_equals_and_hash: nil,
        java_generic_services: nil,
        java_multiple_files: nil,
        java_outer_classname: nil,
        java_package: nil,
        java_string_check_utf8: nil,
        objc_class_prefix: nil,
        optimize_for: nil,
        php_class_prefix: nil,
        php_metadata_namespace: nil,
        php_namespace: nil,
        py_generic_services: nil,
        ruby_package: "LiveKit::Proto",
        swift_prefix: nil,
        uninterpreted_option: []
      },
      name: LivekitProtocolEx.EncryptedPacketPayload,
      syntax: :proto3
    }
  end
end
