# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LivekitProtocolEx.ImageCodec do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :IC_DEFAULT
    def default() do
      :IC_DEFAULT
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:IC_DEFAULT) do
    0
  end

  def encode(:IC_JPEG) do
    1
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :IC_DEFAULT
  end

  def decode(1) do
    :IC_JPEG
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [{0, :IC_DEFAULT}, {1, :IC_JPEG}]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:IC_DEFAULT) do
      true
    end

    def has_constant?(:IC_JPEG) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
