# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LivekitProtocolEx.JobStatus do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :JS_PENDING
    def default() do
      :JS_PENDING
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:JS_PENDING) do
    0
  end

  def encode(:JS_RUNNING) do
    1
  end

  def encode(:JS_SUCCESS) do
    2
  end

  def encode(:JS_FAILED) do
    3
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :JS_PENDING
  end

  def decode(1) do
    :JS_RUNNING
  end

  def decode(2) do
    :JS_SUCCESS
  end

  def decode(3) do
    :JS_FAILED
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [{0, :JS_PENDING}, {1, :JS_RUNNING}, {2, :JS_SUCCESS}, {3, :JS_FAILED}]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:JS_PENDING) do
      true
    end

    def has_constant?(:JS_RUNNING) do
      true
    end

    def has_constant?(:JS_SUCCESS) do
      true
    end

    def has_constant?(:JS_FAILED) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
