# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LivekitProtocolEx.ProviderType do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :PROVIDER_TYPE_UNKNOWN
    def default() do
      :PROVIDER_TYPE_UNKNOWN
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:PROVIDER_TYPE_UNKNOWN) do
    0
  end

  def encode(:PROVIDER_TYPE_INTERNAL) do
    1
  end

  def encode(:PROVIDER_TYPE_EXTERNAL) do
    2
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :PROVIDER_TYPE_UNKNOWN
  end

  def decode(1) do
    :PROVIDER_TYPE_INTERNAL
  end

  def decode(2) do
    :PROVIDER_TYPE_EXTERNAL
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [{0, :PROVIDER_TYPE_UNKNOWN}, {1, :PROVIDER_TYPE_INTERNAL}, {2, :PROVIDER_TYPE_EXTERNAL}]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:PROVIDER_TYPE_UNKNOWN) do
      true
    end

    def has_constant?(:PROVIDER_TYPE_INTERNAL) do
      true
    end

    def has_constant?(:PROVIDER_TYPE_EXTERNAL) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
