# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LivekitProtocolEx.Psrpc.Routing do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :QUEUE
    def default() do
      :QUEUE
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:QUEUE) do
    0
  end

  def encode(:AFFINITY) do
    1
  end

  def encode(:MULTI) do
    2
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :QUEUE
  end

  def decode(1) do
    :AFFINITY
  end

  def decode(2) do
    :MULTI
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [{0, :QUEUE}, {1, :AFFINITY}, {2, :MULTI}]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:QUEUE) do
      true
    end

    def has_constant?(:AFFINITY) do
      true
    end

    def has_constant?(:MULTI) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
