# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LivekitProtocolEx.SegmentedFileOutput do
  @moduledoc false
  if function_exported?(Protox, :check_generator_version, 1) do
    Protox.check_generator_version(1)
  else
    raise "This code was generated with protox 2 but the runtime is using an older version of protox."
  end

  @type t :: %__MODULE__{
          live_playlist_name: String.t(),
          filename_suffix: atom(),
          disable_manifest: boolean(),
          segment_duration: non_neg_integer(),
          playlist_name: String.t(),
          filename_prefix: String.t(),
          protocol: atom(),
          output:
            {:s3, LivekitProtocolEx.S3Upload.t()}
            | {:gcp, LivekitProtocolEx.GCPUpload.t()}
            | {:azure, LivekitProtocolEx.AzureBlobUpload.t()}
            | {:aliOSS, LivekitProtocolEx.AliOSSUpload.t()}
            | nil,
          __uf__: [{non_neg_integer(), Protox.Types.tag(), binary()}]
        }
  defstruct live_playlist_name: "",
            filename_suffix: :INDEX,
            output: nil,
            disable_manifest: false,
            segment_duration: 0,
            playlist_name: "",
            filename_prefix: "",
            protocol: :DEFAULT_SEGMENTED_FILE_PROTOCOL,
            __uf__: []

  (
    (
      @spec encode(t()) :: {:ok, iodata(), non_neg_integer()} | {:error, any()}
      def encode(msg) do
        msg |> encode!() |> Tuple.insert_at(0, :ok)
      rescue
        e in [Protox.EncodingError, Protox.RequiredFieldsError] -> {:error, e}
      end

      @spec encode!(t()) :: {iodata(), non_neg_integer()} | no_return()
      def encode!(msg) do
        {_acc = [], _acc_size = 0}
        |> encode_output(msg)
        |> encode_live_playlist_name(msg)
        |> encode_filename_suffix(msg)
        |> encode_disable_manifest(msg)
        |> encode_segment_duration(msg)
        |> encode_playlist_name(msg)
        |> encode_filename_prefix(msg)
        |> encode_protocol(msg)
        |> encode_unknown_fields(msg)
      end
    )

    defp encode_output({acc, acc_size}, msg) do
      case msg.output do
        nil ->
          {acc, acc_size}

        {:aliOSS, child_field_value} ->
          {value_bytes, value_bytes_size} = Protox.Encode.encode_message(child_field_value)
          {["J", value_bytes | acc], acc_size + 1 + value_bytes_size}

        {:azure, child_field_value} ->
          {value_bytes, value_bytes_size} = Protox.Encode.encode_message(child_field_value)
          {[":", value_bytes | acc], acc_size + 1 + value_bytes_size}

        {:gcp, child_field_value} ->
          {value_bytes, value_bytes_size} = Protox.Encode.encode_message(child_field_value)
          {["2", value_bytes | acc], acc_size + 1 + value_bytes_size}

        {:s3, child_field_value} ->
          {value_bytes, value_bytes_size} = Protox.Encode.encode_message(child_field_value)
          {["*", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    end

    defp encode_live_playlist_name({acc, acc_size}, msg) do
      if msg.live_playlist_name == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.live_playlist_name)
        {["Z", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:live_playlist_name, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_filename_suffix({acc, acc_size}, msg) do
      if msg.filename_suffix == :INDEX do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} =
          msg.filename_suffix
          |> LivekitProtocolEx.SegmentedFileSuffix.encode()
          |> Protox.Encode.encode_enum()

        {["P", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:filename_suffix, "invalid field value"), __STACKTRACE__
    end

    defp encode_disable_manifest({acc, acc_size}, msg) do
      if msg.disable_manifest == false do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_bool(msg.disable_manifest)
        {["@", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:disable_manifest, "invalid field value"), __STACKTRACE__
    end

    defp encode_segment_duration({acc, acc_size}, msg) do
      if msg.segment_duration == 0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_uint32(msg.segment_duration)
        {[" ", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:segment_duration, "invalid field value"), __STACKTRACE__
    end

    defp encode_playlist_name({acc, acc_size}, msg) do
      if msg.playlist_name == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.playlist_name)
        {["\x1A", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:playlist_name, "invalid field value"), __STACKTRACE__
    end

    defp encode_filename_prefix({acc, acc_size}, msg) do
      if msg.filename_prefix == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.filename_prefix)
        {["\x12", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:filename_prefix, "invalid field value"), __STACKTRACE__
    end

    defp encode_protocol({acc, acc_size}, msg) do
      if msg.protocol == :DEFAULT_SEGMENTED_FILE_PROTOCOL do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} =
          msg.protocol
          |> LivekitProtocolEx.SegmentedFileProtocol.encode()
          |> Protox.Encode.encode_enum()

        {["\b", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:protocol, "invalid field value"), __STACKTRACE__
    end

    defp encode_unknown_fields({acc, acc_size}, msg) do
      Enum.reduce(msg.__uf__, {acc, acc_size}, fn {tag, wire_type, bytes}, {acc, acc_size} ->
        case wire_type do
          0 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :int32)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}

          1 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :double)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}

          2 ->
            {len_bytes, len_size} = bytes |> byte_size() |> Protox.Varint.encode()
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :packed)

            {[acc, <<key_bytes::binary, len_bytes::binary, bytes::binary>>],
             acc_size + key_size + len_size + byte_size(bytes)}

          5 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :float)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}
        end
      end)
    end
  )

  (
    (
      @spec decode(binary()) :: {:ok, t()} | {:error, any()}
      def decode(bytes) do
        {:ok, decode!(bytes)}
      rescue
        e in [Protox.DecodingError, Protox.IllegalTagError, Protox.RequiredFieldsError] ->
          {:error, e}
      end

      (
        @spec decode!(binary()) :: t() | no_return()
        def decode!(bytes) do
          parse_key_value(bytes, struct(LivekitProtocolEx.SegmentedFileOutput))
        end
      )
    )

    (
      @spec parse_key_value(binary(), struct()) :: struct()
      defp parse_key_value(<<>>, msg) do
        msg
      end

      defp parse_key_value(bytes, msg) do
        {field, rest} =
          case bytes do
            <<_::5, 3::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 3")

            <<_::5, 4::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 4")

            <<_::5, 6::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 6")

            <<_::5, 7::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 7")

            <<0::5, _::3, _rest::binary>> ->
              raise %Protox.IllegalTagError{}

            <<11::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[live_playlist_name: Protox.Decode.validate_string!(delimited)], rest}

            <<10::5, _wire_type::3, bytes::binary>> ->
              {value, rest} =
                Protox.Decode.parse_enum(bytes, LivekitProtocolEx.SegmentedFileSuffix)

              {[filename_suffix: value], rest}

            <<9::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 case msg.output do
                   {:aliOSS, previous_value} ->
                     {:output,
                      {:aliOSS,
                       Protox.MergeMessage.merge(
                         previous_value,
                         LivekitProtocolEx.AliOSSUpload.decode!(delimited)
                       )}}

                   _ ->
                     {:output, {:aliOSS, LivekitProtocolEx.AliOSSUpload.decode!(delimited)}}
                 end
               ], rest}

            <<8::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_bool(bytes)
              {[disable_manifest: value], rest}

            <<7::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 case msg.output do
                   {:azure, previous_value} ->
                     {:output,
                      {:azure,
                       Protox.MergeMessage.merge(
                         previous_value,
                         LivekitProtocolEx.AzureBlobUpload.decode!(delimited)
                       )}}

                   _ ->
                     {:output, {:azure, LivekitProtocolEx.AzureBlobUpload.decode!(delimited)}}
                 end
               ], rest}

            <<6::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 case msg.output do
                   {:gcp, previous_value} ->
                     {:output,
                      {:gcp,
                       Protox.MergeMessage.merge(
                         previous_value,
                         LivekitProtocolEx.GCPUpload.decode!(delimited)
                       )}}

                   _ ->
                     {:output, {:gcp, LivekitProtocolEx.GCPUpload.decode!(delimited)}}
                 end
               ], rest}

            <<5::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 case msg.output do
                   {:s3, previous_value} ->
                     {:output,
                      {:s3,
                       Protox.MergeMessage.merge(
                         previous_value,
                         LivekitProtocolEx.S3Upload.decode!(delimited)
                       )}}

                   _ ->
                     {:output, {:s3, LivekitProtocolEx.S3Upload.decode!(delimited)}}
                 end
               ], rest}

            <<4::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_uint32(bytes)
              {[segment_duration: value], rest}

            <<3::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[playlist_name: Protox.Decode.validate_string!(delimited)], rest}

            <<2::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[filename_prefix: Protox.Decode.validate_string!(delimited)], rest}

            <<1::5, _wire_type::3, bytes::binary>> ->
              {value, rest} =
                Protox.Decode.parse_enum(bytes, LivekitProtocolEx.SegmentedFileProtocol)

              {[protocol: value], rest}

            <<bytes::binary>> ->
              {tag, wire_type, rest} = Protox.Decode.parse_key(bytes)
              {value, rest} = Protox.Decode.parse_unknown(tag, wire_type, rest)
              {[__uf__: msg.__uf__ ++ [value]], rest}
          end

        msg_updated = struct(msg, field)
        parse_key_value(rest, msg_updated)
      end
    )
  )

  (
    @spec unknown_fields(struct()) :: [{non_neg_integer(), Protox.Types.tag(), binary()}]
    def unknown_fields(msg) do
      msg.__uf__
    end

    @spec unknown_fields_name() :: :__uf__
    def unknown_fields_name() do
      :__uf__
    end

    @spec clear_unknown_fields(struct) :: struct
    def clear_unknown_fields(msg) do
      struct!(msg, __uf__: [])
    end
  )

  (
    @spec default(atom()) ::
            {:ok, boolean() | integer() | String.t() | float()}
            | {:error, :no_such_field | :no_default_value}
    def default(:live_playlist_name) do
      {:ok, ""}
    end

    def default(:filename_suffix) do
      {:ok, :INDEX}
    end

    def default(:aliOSS) do
      {:error, :no_default_value}
    end

    def default(:disable_manifest) do
      {:ok, false}
    end

    def default(:azure) do
      {:error, :no_default_value}
    end

    def default(:gcp) do
      {:error, :no_default_value}
    end

    def default(:s3) do
      {:error, :no_default_value}
    end

    def default(:segment_duration) do
      {:ok, 0}
    end

    def default(:playlist_name) do
      {:ok, ""}
    end

    def default(:filename_prefix) do
      {:ok, ""}
    end

    def default(:protocol) do
      {:ok, :DEFAULT_SEGMENTED_FILE_PROTOCOL}
    end

    def default(_) do
      {:error, :no_such_field}
    end
  )

  @spec schema() :: Protox.MessageSchema.t()
  def schema() do
    %{
      __struct__: Protox.MessageSchema,
      fields: %{
        aliOSS: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.OneOf, parent: :output},
          label: :optional,
          name: :aliOSS,
          tag: 9,
          type: {:message, LivekitProtocolEx.AliOSSUpload}
        },
        azure: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.OneOf, parent: :output},
          label: :optional,
          name: :azure,
          tag: 7,
          type: {:message, LivekitProtocolEx.AzureBlobUpload}
        },
        disable_manifest: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: false},
          label: :optional,
          name: :disable_manifest,
          tag: 8,
          type: :bool
        },
        filename_prefix: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :filename_prefix,
          tag: 2,
          type: :string
        },
        filename_suffix: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: :INDEX},
          label: :optional,
          name: :filename_suffix,
          tag: 10,
          type: {:enum, LivekitProtocolEx.SegmentedFileSuffix}
        },
        gcp: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.OneOf, parent: :output},
          label: :optional,
          name: :gcp,
          tag: 6,
          type: {:message, LivekitProtocolEx.GCPUpload}
        },
        live_playlist_name: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :live_playlist_name,
          tag: 11,
          type: :string
        },
        playlist_name: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :playlist_name,
          tag: 3,
          type: :string
        },
        protocol: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: :DEFAULT_SEGMENTED_FILE_PROTOCOL},
          label: :optional,
          name: :protocol,
          tag: 1,
          type: {:enum, LivekitProtocolEx.SegmentedFileProtocol}
        },
        s3: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.OneOf, parent: :output},
          label: :optional,
          name: :s3,
          tag: 5,
          type: {:message, LivekitProtocolEx.S3Upload}
        },
        segment_duration: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0},
          label: :optional,
          name: :segment_duration,
          tag: 4,
          type: :uint32
        }
      },
      file_options: %{
        cc_enable_arenas: nil,
        cc_generic_services: nil,
        csharp_namespace: "LiveKit.Proto",
        deprecated: nil,
        features: nil,
        go_package: "github.com/livekit/protocol/livekit",
        java_generate_equals_and_hash: nil,
        java_generic_services: nil,
        java_multiple_files: nil,
        java_outer_classname: nil,
        java_package: nil,
        java_string_check_utf8: nil,
        objc_class_prefix: nil,
        optimize_for: nil,
        php_class_prefix: nil,
        php_metadata_namespace: nil,
        php_namespace: nil,
        py_generic_services: nil,
        ruby_package: "LiveKit::Proto",
        swift_prefix: nil,
        uninterpreted_option: []
      },
      name: LivekitProtocolEx.SegmentedFileOutput,
      syntax: :proto3
    }
  end
end
