# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LivekitProtocolEx.ServerInfo.Edition do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :Standard
    def default() do
      :Standard
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:Standard) do
    0
  end

  def encode(:Cloud) do
    1
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :Standard
  end

  def decode(1) do
    :Cloud
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [{0, :Standard}, {1, :Cloud}]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:Standard) do
      true
    end

    def has_constant?(:Cloud) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
