# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LivekitProtocolEx.SignalTarget do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :PUBLISHER
    def default() do
      :PUBLISHER
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:PUBLISHER) do
    0
  end

  def encode(:SUBSCRIBER) do
    1
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :PUBLISHER
  end

  def decode(1) do
    :SUBSCRIBER
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [{0, :PUBLISHER}, {1, :SUBSCRIBER}]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:PUBLISHER) do
      true
    end

    def has_constant?(:SUBSCRIBER) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
