# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LivekitProtocolEx.SIPTransferStatus do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :STS_TRANSFER_ONGOING
    def default() do
      :STS_TRANSFER_ONGOING
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:STS_TRANSFER_ONGOING) do
    0
  end

  def encode(:STS_TRANSFER_FAILED) do
    1
  end

  def encode(:STS_TRANSFER_SUCCESSFUL) do
    2
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :STS_TRANSFER_ONGOING
  end

  def decode(1) do
    :STS_TRANSFER_FAILED
  end

  def decode(2) do
    :STS_TRANSFER_SUCCESSFUL
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [{0, :STS_TRANSFER_ONGOING}, {1, :STS_TRANSFER_FAILED}, {2, :STS_TRANSFER_SUCCESSFUL}]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:STS_TRANSFER_ONGOING) do
      true
    end

    def has_constant?(:STS_TRANSFER_FAILED) do
      true
    end

    def has_constant?(:STS_TRANSFER_SUCCESSFUL) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
