# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LivekitProtocolEx.SIPTransport do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :SIP_TRANSPORT_AUTO
    def default() do
      :SIP_TRANSPORT_AUTO
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:SIP_TRANSPORT_AUTO) do
    0
  end

  def encode(:SIP_TRANSPORT_UDP) do
    1
  end

  def encode(:SIP_TRANSPORT_TCP) do
    2
  end

  def encode(:SIP_TRANSPORT_TLS) do
    3
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :SIP_TRANSPORT_AUTO
  end

  def decode(1) do
    :SIP_TRANSPORT_UDP
  end

  def decode(2) do
    :SIP_TRANSPORT_TCP
  end

  def decode(3) do
    :SIP_TRANSPORT_TLS
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [
      {0, :SIP_TRANSPORT_AUTO},
      {1, :SIP_TRANSPORT_UDP},
      {2, :SIP_TRANSPORT_TCP},
      {3, :SIP_TRANSPORT_TLS}
    ]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:SIP_TRANSPORT_AUTO) do
      true
    end

    def has_constant?(:SIP_TRANSPORT_UDP) do
      true
    end

    def has_constant?(:SIP_TRANSPORT_TCP) do
      true
    end

    def has_constant?(:SIP_TRANSPORT_TLS) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
