# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LivekitProtocolEx.SIPCallDirection do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :SCD_UNKNOWN
    def default() do
      :SCD_UNKNOWN
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:SCD_UNKNOWN) do
    0
  end

  def encode(:SCD_INBOUND) do
    1
  end

  def encode(:SCD_OUTBOUND) do
    2
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :SCD_UNKNOWN
  end

  def decode(1) do
    :SCD_INBOUND
  end

  def decode(2) do
    :SCD_OUTBOUND
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [{0, :SCD_UNKNOWN}, {1, :SCD_INBOUND}, {2, :SCD_OUTBOUND}]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:SCD_UNKNOWN) do
      true
    end

    def has_constant?(:SCD_INBOUND) do
      true
    end

    def has_constant?(:SCD_OUTBOUND) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
