# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LivekitProtocolEx.StreamProtocol do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :DEFAULT_PROTOCOL
    def default() do
      :DEFAULT_PROTOCOL
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:DEFAULT_PROTOCOL) do
    0
  end

  def encode(:RTMP) do
    1
  end

  def encode(:SRT) do
    2
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :DEFAULT_PROTOCOL
  end

  def decode(1) do
    :RTMP
  end

  def decode(2) do
    :SRT
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [{0, :DEFAULT_PROTOCOL}, {1, :RTMP}, {2, :SRT}]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:DEFAULT_PROTOCOL) do
      true
    end

    def has_constant?(:RTMP) do
      true
    end

    def has_constant?(:SRT) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
