# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LivekitProtocolEx.VideoLayer.Mode do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :MODE_UNUSED
    def default() do
      :MODE_UNUSED
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:MODE_UNUSED) do
    0
  end

  def encode(:ONE_SPATIAL_LAYER_PER_STREAM) do
    1
  end

  def encode(:MULTIPLE_SPATIAL_LAYERS_PER_STREAM) do
    2
  end

  def encode(:ONE_SPATIAL_LAYER_PER_STREAM_INCOMPLETE_RTCP_SR) do
    3
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :MODE_UNUSED
  end

  def decode(1) do
    :ONE_SPATIAL_LAYER_PER_STREAM
  end

  def decode(2) do
    :MULTIPLE_SPATIAL_LAYERS_PER_STREAM
  end

  def decode(3) do
    :ONE_SPATIAL_LAYER_PER_STREAM_INCOMPLETE_RTCP_SR
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [
      {0, :MODE_UNUSED},
      {1, :ONE_SPATIAL_LAYER_PER_STREAM},
      {2, :MULTIPLE_SPATIAL_LAYERS_PER_STREAM},
      {3, :ONE_SPATIAL_LAYER_PER_STREAM_INCOMPLETE_RTCP_SR}
    ]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:MODE_UNUSED) do
      true
    end

    def has_constant?(:ONE_SPATIAL_LAYER_PER_STREAM) do
      true
    end

    def has_constant?(:MULTIPLE_SPATIAL_LAYERS_PER_STREAM) do
      true
    end

    def has_constant?(:ONE_SPATIAL_LAYER_PER_STREAM_INCOMPLETE_RTCP_SR) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
