# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LivekitProtocolEx.VideoQuality do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :LOW
    def default() do
      :LOW
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:LOW) do
    0
  end

  def encode(:MEDIUM) do
    1
  end

  def encode(:HIGH) do
    2
  end

  def encode(:OFF) do
    3
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :LOW
  end

  def decode(1) do
    :MEDIUM
  end

  def decode(2) do
    :HIGH
  end

  def decode(3) do
    :OFF
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [{0, :LOW}, {1, :MEDIUM}, {2, :HIGH}, {3, :OFF}]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:LOW) do
      true
    end

    def has_constant?(:MEDIUM) do
      true
    end

    def has_constant?(:HIGH) do
      true
    end

    def has_constant?(:OFF) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
