# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LiveKitProtocolEx.ICECandidateType do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :ICT_NONE
    def default() do
      :ICT_NONE
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:ICT_NONE) do
    0
  end

  def encode(:ICT_TCP) do
    1
  end

  def encode(:ICT_TLS) do
    2
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :ICT_NONE
  end

  def decode(1) do
    :ICT_TCP
  end

  def decode(2) do
    :ICT_TLS
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [{0, :ICT_NONE}, {1, :ICT_TCP}, {2, :ICT_TLS}]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:ICT_NONE) do
      true
    end

    def has_constant?(:ICT_TCP) do
      true
    end

    def has_constant?(:ICT_TLS) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
