# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LiveKitProtocolEx.NodeStatsRate do
  @moduledoc false
  if function_exported?(Protox, :check_generator_version, 1) do
    Protox.check_generator_version(1)
  else
    raise "This code was generated with protox 2 but the runtime is using an older version of protox."
  end

  @type t :: %__MODULE__{
          memory_total: float(),
          memory_used: float(),
          memory_load: float(),
          cpu_load: float(),
          participant_rtc_init: float(),
          participant_rtc_connected: float(),
          participant_signal_connected: float(),
          retransmit_packets_out: float(),
          retransmit_bytes_out: float(),
          sys_packets_dropped: float(),
          sys_packets_out: float(),
          nack_total: float(),
          packets_out: float(),
          packets_in: float(),
          bytes_out: float(),
          bytes_in: float(),
          track_subscribe_success: float(),
          track_subscribe_attempts: float(),
          track_publish_success: float(),
          track_publish_attempts: float(),
          duration: integer(),
          ended_at: integer(),
          started_at: integer(),
          __uf__: [{non_neg_integer(), Protox.Types.tag(), binary()}]
        }
  defstruct memory_total: 0.0,
            memory_used: 0.0,
            memory_load: 0.0,
            cpu_load: 0.0,
            participant_rtc_init: 0.0,
            participant_rtc_connected: 0.0,
            participant_signal_connected: 0.0,
            retransmit_packets_out: 0.0,
            retransmit_bytes_out: 0.0,
            sys_packets_dropped: 0.0,
            sys_packets_out: 0.0,
            nack_total: 0.0,
            packets_out: 0.0,
            packets_in: 0.0,
            bytes_out: 0.0,
            bytes_in: 0.0,
            track_subscribe_success: 0.0,
            track_subscribe_attempts: 0.0,
            track_publish_success: 0.0,
            track_publish_attempts: 0.0,
            duration: 0,
            ended_at: 0,
            started_at: 0,
            __uf__: []

  (
    (
      @spec encode(t()) :: {:ok, iodata(), non_neg_integer()} | {:error, any()}
      def encode(msg) do
        msg |> encode!() |> Tuple.insert_at(0, :ok)
      rescue
        e in [Protox.EncodingError, Protox.RequiredFieldsError] -> {:error, e}
      end

      @spec encode!(t()) :: {iodata(), non_neg_integer()} | no_return()
      def encode!(msg) do
        {_acc = [], _acc_size = 0}
        |> encode_memory_total(msg)
        |> encode_memory_used(msg)
        |> encode_memory_load(msg)
        |> encode_cpu_load(msg)
        |> encode_participant_rtc_init(msg)
        |> encode_participant_rtc_connected(msg)
        |> encode_participant_signal_connected(msg)
        |> encode_retransmit_packets_out(msg)
        |> encode_retransmit_bytes_out(msg)
        |> encode_sys_packets_dropped(msg)
        |> encode_sys_packets_out(msg)
        |> encode_nack_total(msg)
        |> encode_packets_out(msg)
        |> encode_packets_in(msg)
        |> encode_bytes_out(msg)
        |> encode_bytes_in(msg)
        |> encode_track_subscribe_success(msg)
        |> encode_track_subscribe_attempts(msg)
        |> encode_track_publish_success(msg)
        |> encode_track_publish_attempts(msg)
        |> encode_duration(msg)
        |> encode_ended_at(msg)
        |> encode_started_at(msg)
        |> encode_unknown_fields(msg)
      end
    )

    defp encode_memory_total({acc, acc_size}, msg) do
      if msg.memory_total == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_float(msg.memory_total)
        {["\xBD\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:memory_total, "invalid field value"), __STACKTRACE__
    end

    defp encode_memory_used({acc, acc_size}, msg) do
      if msg.memory_used == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_float(msg.memory_used)
        {["\xB5\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:memory_used, "invalid field value"), __STACKTRACE__
    end

    defp encode_memory_load({acc, acc_size}, msg) do
      if msg.memory_load == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_float(msg.memory_load)
        {["\xAD\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:memory_load, "invalid field value"), __STACKTRACE__
    end

    defp encode_cpu_load({acc, acc_size}, msg) do
      if msg.cpu_load == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_float(msg.cpu_load)
        {["\xA5\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:cpu_load, "invalid field value"), __STACKTRACE__
    end

    defp encode_participant_rtc_init({acc, acc_size}, msg) do
      if msg.participant_rtc_init == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_float(msg.participant_rtc_init)
        {["\x9D\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:participant_rtc_init, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_participant_rtc_connected({acc, acc_size}, msg) do
      if msg.participant_rtc_connected == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} =
          Protox.Encode.encode_float(msg.participant_rtc_connected)

        {["\x95\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:participant_rtc_connected, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_participant_signal_connected({acc, acc_size}, msg) do
      if msg.participant_signal_connected == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} =
          Protox.Encode.encode_float(msg.participant_signal_connected)

        {["\x8D\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:participant_signal_connected, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_retransmit_packets_out({acc, acc_size}, msg) do
      if msg.retransmit_packets_out == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_float(msg.retransmit_packets_out)
        {["\x85\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:retransmit_packets_out, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_retransmit_bytes_out({acc, acc_size}, msg) do
      if msg.retransmit_bytes_out == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_float(msg.retransmit_bytes_out)
        {["}", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:retransmit_bytes_out, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_sys_packets_dropped({acc, acc_size}, msg) do
      if msg.sys_packets_dropped == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_float(msg.sys_packets_dropped)
        {["u", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:sys_packets_dropped, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_sys_packets_out({acc, acc_size}, msg) do
      if msg.sys_packets_out == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_float(msg.sys_packets_out)
        {["m", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:sys_packets_out, "invalid field value"), __STACKTRACE__
    end

    defp encode_nack_total({acc, acc_size}, msg) do
      if msg.nack_total == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_float(msg.nack_total)
        {["e", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:nack_total, "invalid field value"), __STACKTRACE__
    end

    defp encode_packets_out({acc, acc_size}, msg) do
      if msg.packets_out == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_float(msg.packets_out)
        {["]", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:packets_out, "invalid field value"), __STACKTRACE__
    end

    defp encode_packets_in({acc, acc_size}, msg) do
      if msg.packets_in == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_float(msg.packets_in)
        {["U", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:packets_in, "invalid field value"), __STACKTRACE__
    end

    defp encode_bytes_out({acc, acc_size}, msg) do
      if msg.bytes_out == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_float(msg.bytes_out)
        {["M", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:bytes_out, "invalid field value"), __STACKTRACE__
    end

    defp encode_bytes_in({acc, acc_size}, msg) do
      if msg.bytes_in == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_float(msg.bytes_in)
        {["E", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:bytes_in, "invalid field value"), __STACKTRACE__
    end

    defp encode_track_subscribe_success({acc, acc_size}, msg) do
      if msg.track_subscribe_success == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_float(msg.track_subscribe_success)
        {["=", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:track_subscribe_success, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_track_subscribe_attempts({acc, acc_size}, msg) do
      if msg.track_subscribe_attempts == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_float(msg.track_subscribe_attempts)
        {["5", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:track_subscribe_attempts, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_track_publish_success({acc, acc_size}, msg) do
      if msg.track_publish_success == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_float(msg.track_publish_success)
        {["-", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:track_publish_success, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_track_publish_attempts({acc, acc_size}, msg) do
      if msg.track_publish_attempts == 0.0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_float(msg.track_publish_attempts)
        {["%", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:track_publish_attempts, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_duration({acc, acc_size}, msg) do
      if msg.duration == 0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_int64(msg.duration)
        {["\x18", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:duration, "invalid field value"), __STACKTRACE__
    end

    defp encode_ended_at({acc, acc_size}, msg) do
      if msg.ended_at == 0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_int64(msg.ended_at)
        {["\x10", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:ended_at, "invalid field value"), __STACKTRACE__
    end

    defp encode_started_at({acc, acc_size}, msg) do
      if msg.started_at == 0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_int64(msg.started_at)
        {["\b", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:started_at, "invalid field value"), __STACKTRACE__
    end

    defp encode_unknown_fields({acc, acc_size}, msg) do
      Enum.reduce(msg.__uf__, {acc, acc_size}, fn {tag, wire_type, bytes}, {acc, acc_size} ->
        case wire_type do
          0 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :int32)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}

          1 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :double)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}

          2 ->
            {len_bytes, len_size} = bytes |> byte_size() |> Protox.Varint.encode()
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :packed)

            {[acc, <<key_bytes::binary, len_bytes::binary, bytes::binary>>],
             acc_size + key_size + len_size + byte_size(bytes)}

          5 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :float)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}
        end
      end)
    end
  )

  (
    (
      @spec decode(binary()) :: {:ok, t()} | {:error, any()}
      def decode(bytes) do
        {:ok, decode!(bytes)}
      rescue
        e in [Protox.DecodingError, Protox.IllegalTagError, Protox.RequiredFieldsError] ->
          {:error, e}
      end

      (
        @spec decode!(binary()) :: t() | no_return()
        def decode!(bytes) do
          parse_key_value(bytes, struct(LiveKitProtocolEx.NodeStatsRate))
        end
      )
    )

    (
      @spec parse_key_value(binary(), struct()) :: struct()
      defp parse_key_value(<<>>, msg) do
        msg
      end

      defp parse_key_value(bytes, msg) do
        {field, rest} =
          case bytes do
            <<_::5, 3::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 3")

            <<_::5, 4::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 4")

            <<_::5, 6::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 6")

            <<_::5, 7::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 7")

            <<0::5, _::3, _rest::binary>> ->
              raise %Protox.IllegalTagError{}

            <<23::5, _wire_type::3, "\x01", bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[memory_total: value], rest}

            <<22::5, _wire_type::3, "\x01", bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[memory_used: value], rest}

            <<21::5, _wire_type::3, "\x01", bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[memory_load: value], rest}

            <<20::5, _wire_type::3, "\x01", bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[cpu_load: value], rest}

            <<19::5, _wire_type::3, "\x01", bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[participant_rtc_init: value], rest}

            <<18::5, _wire_type::3, "\x01", bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[participant_rtc_connected: value], rest}

            <<17::5, _wire_type::3, "\x01", bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[participant_signal_connected: value], rest}

            <<16::5, _wire_type::3, "\x01", bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[retransmit_packets_out: value], rest}

            <<15::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[retransmit_bytes_out: value], rest}

            <<14::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[sys_packets_dropped: value], rest}

            <<13::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[sys_packets_out: value], rest}

            <<12::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[nack_total: value], rest}

            <<11::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[packets_out: value], rest}

            <<10::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[packets_in: value], rest}

            <<9::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[bytes_out: value], rest}

            <<8::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[bytes_in: value], rest}

            <<7::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[track_subscribe_success: value], rest}

            <<6::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[track_subscribe_attempts: value], rest}

            <<5::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[track_publish_success: value], rest}

            <<4::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_float(bytes)
              {[track_publish_attempts: value], rest}

            <<3::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_int64(bytes)
              {[duration: value], rest}

            <<2::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_int64(bytes)
              {[ended_at: value], rest}

            <<1::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_int64(bytes)
              {[started_at: value], rest}

            <<bytes::binary>> ->
              {tag, wire_type, rest} = Protox.Decode.parse_key(bytes)
              {value, rest} = Protox.Decode.parse_unknown(tag, wire_type, rest)
              {[__uf__: msg.__uf__ ++ [value]], rest}
          end

        msg_updated = struct(msg, field)
        parse_key_value(rest, msg_updated)
      end
    )
  )

  (
    @spec unknown_fields(struct()) :: [{non_neg_integer(), Protox.Types.tag(), binary()}]
    def unknown_fields(msg) do
      msg.__uf__
    end

    @spec unknown_fields_name() :: :__uf__
    def unknown_fields_name() do
      :__uf__
    end

    @spec clear_unknown_fields(struct) :: struct
    def clear_unknown_fields(msg) do
      struct!(msg, __uf__: [])
    end
  )

  (
    @spec default(atom()) ::
            {:ok, boolean() | integer() | String.t() | float()}
            | {:error, :no_such_field | :no_default_value}
    def default(:memory_total) do
      {:ok, 0.0}
    end

    def default(:memory_used) do
      {:ok, 0.0}
    end

    def default(:memory_load) do
      {:ok, 0.0}
    end

    def default(:cpu_load) do
      {:ok, 0.0}
    end

    def default(:participant_rtc_init) do
      {:ok, 0.0}
    end

    def default(:participant_rtc_connected) do
      {:ok, 0.0}
    end

    def default(:participant_signal_connected) do
      {:ok, 0.0}
    end

    def default(:retransmit_packets_out) do
      {:ok, 0.0}
    end

    def default(:retransmit_bytes_out) do
      {:ok, 0.0}
    end

    def default(:sys_packets_dropped) do
      {:ok, 0.0}
    end

    def default(:sys_packets_out) do
      {:ok, 0.0}
    end

    def default(:nack_total) do
      {:ok, 0.0}
    end

    def default(:packets_out) do
      {:ok, 0.0}
    end

    def default(:packets_in) do
      {:ok, 0.0}
    end

    def default(:bytes_out) do
      {:ok, 0.0}
    end

    def default(:bytes_in) do
      {:ok, 0.0}
    end

    def default(:track_subscribe_success) do
      {:ok, 0.0}
    end

    def default(:track_subscribe_attempts) do
      {:ok, 0.0}
    end

    def default(:track_publish_success) do
      {:ok, 0.0}
    end

    def default(:track_publish_attempts) do
      {:ok, 0.0}
    end

    def default(:duration) do
      {:ok, 0}
    end

    def default(:ended_at) do
      {:ok, 0}
    end

    def default(:started_at) do
      {:ok, 0}
    end

    def default(_) do
      {:error, :no_such_field}
    end
  )

  @spec schema() :: Protox.MessageSchema.t()
  def schema() do
    %{
      __struct__: Protox.MessageSchema,
      fields: %{
        bytes_in: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :bytes_in,
          tag: 8,
          type: :float
        },
        bytes_out: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :bytes_out,
          tag: 9,
          type: :float
        },
        cpu_load: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :cpu_load,
          tag: 20,
          type: :float
        },
        duration: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0},
          label: :optional,
          name: :duration,
          tag: 3,
          type: :int64
        },
        ended_at: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0},
          label: :optional,
          name: :ended_at,
          tag: 2,
          type: :int64
        },
        memory_load: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :memory_load,
          tag: 21,
          type: :float
        },
        memory_total: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :memory_total,
          tag: 23,
          type: :float
        },
        memory_used: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :memory_used,
          tag: 22,
          type: :float
        },
        nack_total: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :nack_total,
          tag: 12,
          type: :float
        },
        packets_in: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :packets_in,
          tag: 10,
          type: :float
        },
        packets_out: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :packets_out,
          tag: 11,
          type: :float
        },
        participant_rtc_connected: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :participant_rtc_connected,
          tag: 18,
          type: :float
        },
        participant_rtc_init: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :participant_rtc_init,
          tag: 19,
          type: :float
        },
        participant_signal_connected: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :participant_signal_connected,
          tag: 17,
          type: :float
        },
        retransmit_bytes_out: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :retransmit_bytes_out,
          tag: 15,
          type: :float
        },
        retransmit_packets_out: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :retransmit_packets_out,
          tag: 16,
          type: :float
        },
        started_at: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0},
          label: :optional,
          name: :started_at,
          tag: 1,
          type: :int64
        },
        sys_packets_dropped: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :sys_packets_dropped,
          tag: 14,
          type: :float
        },
        sys_packets_out: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :sys_packets_out,
          tag: 13,
          type: :float
        },
        track_publish_attempts: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :track_publish_attempts,
          tag: 4,
          type: :float
        },
        track_publish_success: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :track_publish_success,
          tag: 5,
          type: :float
        },
        track_subscribe_attempts: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :track_subscribe_attempts,
          tag: 6,
          type: :float
        },
        track_subscribe_success: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: 0.0},
          label: :optional,
          name: :track_subscribe_success,
          tag: 7,
          type: :float
        }
      },
      file_options: %{
        cc_enable_arenas: nil,
        cc_generic_services: nil,
        csharp_namespace: "LiveKit.Proto",
        deprecated: nil,
        features: nil,
        go_package: "github.com/livekit/protocol/livekit",
        java_generate_equals_and_hash: nil,
        java_generic_services: nil,
        java_multiple_files: nil,
        java_outer_classname: nil,
        java_package: nil,
        java_string_check_utf8: nil,
        objc_class_prefix: nil,
        optimize_for: nil,
        php_class_prefix: nil,
        php_metadata_namespace: nil,
        php_namespace: nil,
        py_generic_services: nil,
        ruby_package: "LiveKit::Proto",
        swift_prefix: nil,
        uninterpreted_option: []
      },
      name: LiveKitProtocolEx.NodeStatsRate,
      syntax: :proto3
    }
  end
end
