# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LiveKitProtocolEx.NodeType do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :SERVER
    def default() do
      :SERVER
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:SERVER) do
    0
  end

  def encode(:CONTROLLER) do
    1
  end

  def encode(:MEDIA) do
    2
  end

  def encode(:TURN) do
    4
  end

  def encode(:SWEEPER) do
    5
  end

  def encode(:DIRECTOR) do
    6
  end

  def encode(:HOSTED_AGENT) do
    7
  end

  def encode(:SETTINGS) do
    8
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :SERVER
  end

  def decode(1) do
    :CONTROLLER
  end

  def decode(2) do
    :MEDIA
  end

  def decode(4) do
    :TURN
  end

  def decode(5) do
    :SWEEPER
  end

  def decode(6) do
    :DIRECTOR
  end

  def decode(7) do
    :HOSTED_AGENT
  end

  def decode(8) do
    :SETTINGS
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [
      {0, :SERVER},
      {1, :CONTROLLER},
      {2, :MEDIA},
      {4, :TURN},
      {5, :SWEEPER},
      {6, :DIRECTOR},
      {7, :HOSTED_AGENT},
      {8, :SETTINGS}
    ]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:SERVER) do
      true
    end

    def has_constant?(:CONTROLLER) do
      true
    end

    def has_constant?(:MEDIA) do
      true
    end

    def has_constant?(:TURN) do
      true
    end

    def has_constant?(:SWEEPER) do
      true
    end

    def has_constant?(:DIRECTOR) do
      true
    end

    def has_constant?(:HOSTED_AGENT) do
      true
    end

    def has_constant?(:SETTINGS) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
