# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LiveKitProtocolEx.SIPStatusCode do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :SIP_STATUS_UNKNOWN
    def default() do
      :SIP_STATUS_UNKNOWN
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:SIP_STATUS_UNKNOWN) do
    0
  end

  def encode(:SIP_STATUS_TRYING) do
    100
  end

  def encode(:SIP_STATUS_RINGING) do
    180
  end

  def encode(:SIP_STATUS_CALL_IS_FORWARDED) do
    181
  end

  def encode(:SIP_STATUS_QUEUED) do
    182
  end

  def encode(:SIP_STATUS_SESSION_PROGRESS) do
    183
  end

  def encode(:SIP_STATUS_EARLY_DIALOG_TERMINATED) do
    199
  end

  def encode(:SIP_STATUS_OK) do
    200
  end

  def encode(:SIP_STATUS_ACCEPTED) do
    202
  end

  def encode(:SIP_STATUS_NO_NOTIFICATION) do
    204
  end

  def encode(:SIP_STATUS_MULTIPLE_CHOICES) do
    300
  end

  def encode(:SIP_STATUS_MOVED_PERMANENTLY) do
    301
  end

  def encode(:SIP_STATUS_MOVED_TEMPORARILY) do
    302
  end

  def encode(:SIP_STATUS_USE_PROXY) do
    305
  end

  def encode(:SIP_STATUS_ALTERNATIVE_SERVICE) do
    380
  end

  def encode(:SIP_STATUS_BAD_REQUEST) do
    400
  end

  def encode(:SIP_STATUS_UNAUTHORIZED) do
    401
  end

  def encode(:SIP_STATUS_PAYMENT_REQUIRED) do
    402
  end

  def encode(:SIP_STATUS_FORBIDDEN) do
    403
  end

  def encode(:SIP_STATUS_NOTFOUND) do
    404
  end

  def encode(:SIP_STATUS_METHOD_NOT_ALLOWED) do
    405
  end

  def encode(:SIP_STATUS_NOT_ACCEPTABLE) do
    406
  end

  def encode(:SIP_STATUS_PROXY_AUTH_REQUIRED) do
    407
  end

  def encode(:SIP_STATUS_REQUEST_TIMEOUT) do
    408
  end

  def encode(:SIP_STATUS_CONFLICT) do
    409
  end

  def encode(:SIP_STATUS_GONE) do
    410
  end

  def encode(:SIP_STATUS_LENGTH_REQUIRED) do
    411
  end

  def encode(:SIP_STATUS_CONDITIONAL_REQUEST_FAILED) do
    412
  end

  def encode(:SIP_STATUS_REQUEST_ENTITY_TOO_LARGE) do
    413
  end

  def encode(:SIP_STATUS_REQUEST_URI_TOO_LONG) do
    414
  end

  def encode(:SIP_STATUS_UNSUPPORTED_MEDIA_TYPE) do
    415
  end

  def encode(:SIP_STATUS_REQUESTED_RANGE_NOT_SATISFIABLE) do
    416
  end

  def encode(:SIP_STATUS_UNKNOWN_RESOURCE_PRIORITY) do
    417
  end

  def encode(:SIP_STATUS_BAD_EXTENSION) do
    420
  end

  def encode(:SIP_STATUS_EXTENSION_REQUIRED) do
    421
  end

  def encode(:SIP_STATUS_SESSION_INTERVAL_TOO_SMALL) do
    422
  end

  def encode(:SIP_STATUS_INTERVAL_TOO_BRIEF) do
    423
  end

  def encode(:SIP_STATUS_BAD_LOCATION_INFORMATION) do
    424
  end

  def encode(:SIP_STATUS_BAD_ALERT_MESSAGE) do
    425
  end

  def encode(:SIP_STATUS_USE_IDENTITY_HEADER) do
    428
  end

  def encode(:SIP_STATUS_PROVIDE_REFERRER_IDENTITY) do
    429
  end

  def encode(:SIP_STATUS_FLOW_FAILED) do
    430
  end

  def encode(:SIP_STATUS_ANONYMITY_DISALLOWED) do
    433
  end

  def encode(:SIP_STATUS_BAD_IDENTITY_INFO) do
    436
  end

  def encode(:SIP_STATUS_UNSUPPORTED_CERTIFICATE) do
    437
  end

  def encode(:SIP_STATUS_INVALID_IDENTITY_HEADER) do
    438
  end

  def encode(:SIP_STATUS_FIRST_HOP_LACKS_OUTBOUND_SUPPORT) do
    439
  end

  def encode(:SIP_STATUS_MAX_BREADTH_EXCEEDED) do
    440
  end

  def encode(:SIP_STATUS_BAD_INFO_PACKAGE) do
    469
  end

  def encode(:SIP_STATUS_CONSENT_NEEDED) do
    470
  end

  def encode(:SIP_STATUS_TEMPORARILY_UNAVAILABLE) do
    480
  end

  def encode(:SIP_STATUS_CALL_TRANSACTION_DOES_NOT_EXISTS) do
    481
  end

  def encode(:SIP_STATUS_LOOP_DETECTED) do
    482
  end

  def encode(:SIP_STATUS_TOO_MANY_HOPS) do
    483
  end

  def encode(:SIP_STATUS_ADDRESS_INCOMPLETE) do
    484
  end

  def encode(:SIP_STATUS_AMBIGUOUS) do
    485
  end

  def encode(:SIP_STATUS_BUSY_HERE) do
    486
  end

  def encode(:SIP_STATUS_REQUEST_TERMINATED) do
    487
  end

  def encode(:SIP_STATUS_NOT_ACCEPTABLE_HERE) do
    488
  end

  def encode(:SIP_STATUS_BAD_EVENT) do
    489
  end

  def encode(:SIP_STATUS_REQUEST_PENDING) do
    491
  end

  def encode(:SIP_STATUS_UNDECIPHERABLE) do
    493
  end

  def encode(:SIP_STATUS_SECURITY_AGREEMENT_REQUIRED) do
    494
  end

  def encode(:SIP_STATUS_INTERNAL_SERVER_ERROR) do
    500
  end

  def encode(:SIP_STATUS_NOT_IMPLEMENTED) do
    501
  end

  def encode(:SIP_STATUS_BAD_GATEWAY) do
    502
  end

  def encode(:SIP_STATUS_SERVICE_UNAVAILABLE) do
    503
  end

  def encode(:SIP_STATUS_GATEWAY_TIMEOUT) do
    504
  end

  def encode(:SIP_STATUS_VERSION_NOT_SUPPORTED) do
    505
  end

  def encode(:SIP_STATUS_MESSAGE_TOO_LARGE) do
    513
  end

  def encode(:SIP_STATUS_GLOBAL_BUSY_EVERYWHERE) do
    600
  end

  def encode(:SIP_STATUS_GLOBAL_DECLINE) do
    603
  end

  def encode(:SIP_STATUS_GLOBAL_DOES_NOT_EXIST_ANYWHERE) do
    604
  end

  def encode(:SIP_STATUS_GLOBAL_NOT_ACCEPTABLE) do
    606
  end

  def encode(:SIP_STATUS_GLOBAL_UNWANTED) do
    607
  end

  def encode(:SIP_STATUS_GLOBAL_REJECTED) do
    608
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(513) do
    :SIP_STATUS_MESSAGE_TOO_LARGE
  end

  def decode(436) do
    :SIP_STATUS_BAD_IDENTITY_INFO
  end

  def decode(503) do
    :SIP_STATUS_SERVICE_UNAVAILABLE
  end

  def decode(416) do
    :SIP_STATUS_REQUESTED_RANGE_NOT_SATISFIABLE
  end

  def decode(480) do
    :SIP_STATUS_TEMPORARILY_UNAVAILABLE
  end

  def decode(604) do
    :SIP_STATUS_GLOBAL_DOES_NOT_EXIST_ANYWHERE
  end

  def decode(300) do
    :SIP_STATUS_MULTIPLE_CHOICES
  end

  def decode(415) do
    :SIP_STATUS_UNSUPPORTED_MEDIA_TYPE
  end

  def decode(486) do
    :SIP_STATUS_BUSY_HERE
  end

  def decode(607) do
    :SIP_STATUS_GLOBAL_UNWANTED
  end

  def decode(182) do
    :SIP_STATUS_QUEUED
  end

  def decode(422) do
    :SIP_STATUS_SESSION_INTERVAL_TOO_SMALL
  end

  def decode(421) do
    :SIP_STATUS_EXTENSION_REQUIRED
  end

  def decode(429) do
    :SIP_STATUS_PROVIDE_REFERRER_IDENTITY
  end

  def decode(100) do
    :SIP_STATUS_TRYING
  end

  def decode(202) do
    :SIP_STATUS_ACCEPTED
  end

  def decode(606) do
    :SIP_STATUS_GLOBAL_NOT_ACCEPTABLE
  end

  def decode(470) do
    :SIP_STATUS_CONSENT_NEEDED
  end

  def decode(408) do
    :SIP_STATUS_REQUEST_TIMEOUT
  end

  def decode(424) do
    :SIP_STATUS_BAD_LOCATION_INFORMATION
  end

  def decode(204) do
    :SIP_STATUS_NO_NOTIFICATION
  end

  def decode(403) do
    :SIP_STATUS_FORBIDDEN
  end

  def decode(483) do
    :SIP_STATUS_TOO_MANY_HOPS
  end

  def decode(484) do
    :SIP_STATUS_ADDRESS_INCOMPLETE
  end

  def decode(437) do
    :SIP_STATUS_UNSUPPORTED_CERTIFICATE
  end

  def decode(302) do
    :SIP_STATUS_MOVED_TEMPORARILY
  end

  def decode(181) do
    :SIP_STATUS_CALL_IS_FORWARDED
  end

  def decode(494) do
    :SIP_STATUS_SECURITY_AGREEMENT_REQUIRED
  end

  def decode(410) do
    :SIP_STATUS_GONE
  end

  def decode(440) do
    :SIP_STATUS_MAX_BREADTH_EXCEEDED
  end

  def decode(380) do
    :SIP_STATUS_ALTERNATIVE_SERVICE
  end

  def decode(600) do
    :SIP_STATUS_GLOBAL_BUSY_EVERYWHERE
  end

  def decode(438) do
    :SIP_STATUS_INVALID_IDENTITY_HEADER
  end

  def decode(425) do
    :SIP_STATUS_BAD_ALERT_MESSAGE
  end

  def decode(502) do
    :SIP_STATUS_BAD_GATEWAY
  end

  def decode(183) do
    :SIP_STATUS_SESSION_PROGRESS
  end

  def decode(401) do
    :SIP_STATUS_UNAUTHORIZED
  end

  def decode(430) do
    :SIP_STATUS_FLOW_FAILED
  end

  def decode(481) do
    :SIP_STATUS_CALL_TRANSACTION_DOES_NOT_EXISTS
  end

  def decode(469) do
    :SIP_STATUS_BAD_INFO_PACKAGE
  end

  def decode(180) do
    :SIP_STATUS_RINGING
  end

  def decode(404) do
    :SIP_STATUS_NOTFOUND
  end

  def decode(489) do
    :SIP_STATUS_BAD_EVENT
  end

  def decode(301) do
    :SIP_STATUS_MOVED_PERMANENTLY
  end

  def decode(428) do
    :SIP_STATUS_USE_IDENTITY_HEADER
  end

  def decode(200) do
    :SIP_STATUS_OK
  end

  def decode(504) do
    :SIP_STATUS_GATEWAY_TIMEOUT
  end

  def decode(405) do
    :SIP_STATUS_METHOD_NOT_ALLOWED
  end

  def decode(411) do
    :SIP_STATUS_LENGTH_REQUIRED
  end

  def decode(199) do
    :SIP_STATUS_EARLY_DIALOG_TERMINATED
  end

  def decode(493) do
    :SIP_STATUS_UNDECIPHERABLE
  end

  def decode(608) do
    :SIP_STATUS_GLOBAL_REJECTED
  end

  def decode(439) do
    :SIP_STATUS_FIRST_HOP_LACKS_OUTBOUND_SUPPORT
  end

  def decode(407) do
    :SIP_STATUS_PROXY_AUTH_REQUIRED
  end

  def decode(420) do
    :SIP_STATUS_BAD_EXTENSION
  end

  def decode(501) do
    :SIP_STATUS_NOT_IMPLEMENTED
  end

  def decode(305) do
    :SIP_STATUS_USE_PROXY
  end

  def decode(482) do
    :SIP_STATUS_LOOP_DETECTED
  end

  def decode(406) do
    :SIP_STATUS_NOT_ACCEPTABLE
  end

  def decode(423) do
    :SIP_STATUS_INTERVAL_TOO_BRIEF
  end

  def decode(0) do
    :SIP_STATUS_UNKNOWN
  end

  def decode(433) do
    :SIP_STATUS_ANONYMITY_DISALLOWED
  end

  def decode(488) do
    :SIP_STATUS_NOT_ACCEPTABLE_HERE
  end

  def decode(505) do
    :SIP_STATUS_VERSION_NOT_SUPPORTED
  end

  def decode(412) do
    :SIP_STATUS_CONDITIONAL_REQUEST_FAILED
  end

  def decode(409) do
    :SIP_STATUS_CONFLICT
  end

  def decode(417) do
    :SIP_STATUS_UNKNOWN_RESOURCE_PRIORITY
  end

  def decode(414) do
    :SIP_STATUS_REQUEST_URI_TOO_LONG
  end

  def decode(402) do
    :SIP_STATUS_PAYMENT_REQUIRED
  end

  def decode(500) do
    :SIP_STATUS_INTERNAL_SERVER_ERROR
  end

  def decode(400) do
    :SIP_STATUS_BAD_REQUEST
  end

  def decode(603) do
    :SIP_STATUS_GLOBAL_DECLINE
  end

  def decode(487) do
    :SIP_STATUS_REQUEST_TERMINATED
  end

  def decode(491) do
    :SIP_STATUS_REQUEST_PENDING
  end

  def decode(413) do
    :SIP_STATUS_REQUEST_ENTITY_TOO_LARGE
  end

  def decode(485) do
    :SIP_STATUS_AMBIGUOUS
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [
      {0, :SIP_STATUS_UNKNOWN},
      {100, :SIP_STATUS_TRYING},
      {180, :SIP_STATUS_RINGING},
      {181, :SIP_STATUS_CALL_IS_FORWARDED},
      {182, :SIP_STATUS_QUEUED},
      {183, :SIP_STATUS_SESSION_PROGRESS},
      {199, :SIP_STATUS_EARLY_DIALOG_TERMINATED},
      {200, :SIP_STATUS_OK},
      {202, :SIP_STATUS_ACCEPTED},
      {204, :SIP_STATUS_NO_NOTIFICATION},
      {300, :SIP_STATUS_MULTIPLE_CHOICES},
      {301, :SIP_STATUS_MOVED_PERMANENTLY},
      {302, :SIP_STATUS_MOVED_TEMPORARILY},
      {305, :SIP_STATUS_USE_PROXY},
      {380, :SIP_STATUS_ALTERNATIVE_SERVICE},
      {400, :SIP_STATUS_BAD_REQUEST},
      {401, :SIP_STATUS_UNAUTHORIZED},
      {402, :SIP_STATUS_PAYMENT_REQUIRED},
      {403, :SIP_STATUS_FORBIDDEN},
      {404, :SIP_STATUS_NOTFOUND},
      {405, :SIP_STATUS_METHOD_NOT_ALLOWED},
      {406, :SIP_STATUS_NOT_ACCEPTABLE},
      {407, :SIP_STATUS_PROXY_AUTH_REQUIRED},
      {408, :SIP_STATUS_REQUEST_TIMEOUT},
      {409, :SIP_STATUS_CONFLICT},
      {410, :SIP_STATUS_GONE},
      {411, :SIP_STATUS_LENGTH_REQUIRED},
      {412, :SIP_STATUS_CONDITIONAL_REQUEST_FAILED},
      {413, :SIP_STATUS_REQUEST_ENTITY_TOO_LARGE},
      {414, :SIP_STATUS_REQUEST_URI_TOO_LONG},
      {415, :SIP_STATUS_UNSUPPORTED_MEDIA_TYPE},
      {416, :SIP_STATUS_REQUESTED_RANGE_NOT_SATISFIABLE},
      {417, :SIP_STATUS_UNKNOWN_RESOURCE_PRIORITY},
      {420, :SIP_STATUS_BAD_EXTENSION},
      {421, :SIP_STATUS_EXTENSION_REQUIRED},
      {422, :SIP_STATUS_SESSION_INTERVAL_TOO_SMALL},
      {423, :SIP_STATUS_INTERVAL_TOO_BRIEF},
      {424, :SIP_STATUS_BAD_LOCATION_INFORMATION},
      {425, :SIP_STATUS_BAD_ALERT_MESSAGE},
      {428, :SIP_STATUS_USE_IDENTITY_HEADER},
      {429, :SIP_STATUS_PROVIDE_REFERRER_IDENTITY},
      {430, :SIP_STATUS_FLOW_FAILED},
      {433, :SIP_STATUS_ANONYMITY_DISALLOWED},
      {436, :SIP_STATUS_BAD_IDENTITY_INFO},
      {437, :SIP_STATUS_UNSUPPORTED_CERTIFICATE},
      {438, :SIP_STATUS_INVALID_IDENTITY_HEADER},
      {439, :SIP_STATUS_FIRST_HOP_LACKS_OUTBOUND_SUPPORT},
      {440, :SIP_STATUS_MAX_BREADTH_EXCEEDED},
      {469, :SIP_STATUS_BAD_INFO_PACKAGE},
      {470, :SIP_STATUS_CONSENT_NEEDED},
      {480, :SIP_STATUS_TEMPORARILY_UNAVAILABLE},
      {481, :SIP_STATUS_CALL_TRANSACTION_DOES_NOT_EXISTS},
      {482, :SIP_STATUS_LOOP_DETECTED},
      {483, :SIP_STATUS_TOO_MANY_HOPS},
      {484, :SIP_STATUS_ADDRESS_INCOMPLETE},
      {485, :SIP_STATUS_AMBIGUOUS},
      {486, :SIP_STATUS_BUSY_HERE},
      {487, :SIP_STATUS_REQUEST_TERMINATED},
      {488, :SIP_STATUS_NOT_ACCEPTABLE_HERE},
      {489, :SIP_STATUS_BAD_EVENT},
      {491, :SIP_STATUS_REQUEST_PENDING},
      {493, :SIP_STATUS_UNDECIPHERABLE},
      {494, :SIP_STATUS_SECURITY_AGREEMENT_REQUIRED},
      {500, :SIP_STATUS_INTERNAL_SERVER_ERROR},
      {501, :SIP_STATUS_NOT_IMPLEMENTED},
      {502, :SIP_STATUS_BAD_GATEWAY},
      {503, :SIP_STATUS_SERVICE_UNAVAILABLE},
      {504, :SIP_STATUS_GATEWAY_TIMEOUT},
      {505, :SIP_STATUS_VERSION_NOT_SUPPORTED},
      {513, :SIP_STATUS_MESSAGE_TOO_LARGE},
      {600, :SIP_STATUS_GLOBAL_BUSY_EVERYWHERE},
      {603, :SIP_STATUS_GLOBAL_DECLINE},
      {604, :SIP_STATUS_GLOBAL_DOES_NOT_EXIST_ANYWHERE},
      {606, :SIP_STATUS_GLOBAL_NOT_ACCEPTABLE},
      {607, :SIP_STATUS_GLOBAL_UNWANTED},
      {608, :SIP_STATUS_GLOBAL_REJECTED}
    ]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:SIP_STATUS_UNKNOWN) do
      true
    end

    def has_constant?(:SIP_STATUS_TRYING) do
      true
    end

    def has_constant?(:SIP_STATUS_RINGING) do
      true
    end

    def has_constant?(:SIP_STATUS_CALL_IS_FORWARDED) do
      true
    end

    def has_constant?(:SIP_STATUS_QUEUED) do
      true
    end

    def has_constant?(:SIP_STATUS_SESSION_PROGRESS) do
      true
    end

    def has_constant?(:SIP_STATUS_EARLY_DIALOG_TERMINATED) do
      true
    end

    def has_constant?(:SIP_STATUS_OK) do
      true
    end

    def has_constant?(:SIP_STATUS_ACCEPTED) do
      true
    end

    def has_constant?(:SIP_STATUS_NO_NOTIFICATION) do
      true
    end

    def has_constant?(:SIP_STATUS_MULTIPLE_CHOICES) do
      true
    end

    def has_constant?(:SIP_STATUS_MOVED_PERMANENTLY) do
      true
    end

    def has_constant?(:SIP_STATUS_MOVED_TEMPORARILY) do
      true
    end

    def has_constant?(:SIP_STATUS_USE_PROXY) do
      true
    end

    def has_constant?(:SIP_STATUS_ALTERNATIVE_SERVICE) do
      true
    end

    def has_constant?(:SIP_STATUS_BAD_REQUEST) do
      true
    end

    def has_constant?(:SIP_STATUS_UNAUTHORIZED) do
      true
    end

    def has_constant?(:SIP_STATUS_PAYMENT_REQUIRED) do
      true
    end

    def has_constant?(:SIP_STATUS_FORBIDDEN) do
      true
    end

    def has_constant?(:SIP_STATUS_NOTFOUND) do
      true
    end

    def has_constant?(:SIP_STATUS_METHOD_NOT_ALLOWED) do
      true
    end

    def has_constant?(:SIP_STATUS_NOT_ACCEPTABLE) do
      true
    end

    def has_constant?(:SIP_STATUS_PROXY_AUTH_REQUIRED) do
      true
    end

    def has_constant?(:SIP_STATUS_REQUEST_TIMEOUT) do
      true
    end

    def has_constant?(:SIP_STATUS_CONFLICT) do
      true
    end

    def has_constant?(:SIP_STATUS_GONE) do
      true
    end

    def has_constant?(:SIP_STATUS_LENGTH_REQUIRED) do
      true
    end

    def has_constant?(:SIP_STATUS_CONDITIONAL_REQUEST_FAILED) do
      true
    end

    def has_constant?(:SIP_STATUS_REQUEST_ENTITY_TOO_LARGE) do
      true
    end

    def has_constant?(:SIP_STATUS_REQUEST_URI_TOO_LONG) do
      true
    end

    def has_constant?(:SIP_STATUS_UNSUPPORTED_MEDIA_TYPE) do
      true
    end

    def has_constant?(:SIP_STATUS_REQUESTED_RANGE_NOT_SATISFIABLE) do
      true
    end

    def has_constant?(:SIP_STATUS_UNKNOWN_RESOURCE_PRIORITY) do
      true
    end

    def has_constant?(:SIP_STATUS_BAD_EXTENSION) do
      true
    end

    def has_constant?(:SIP_STATUS_EXTENSION_REQUIRED) do
      true
    end

    def has_constant?(:SIP_STATUS_SESSION_INTERVAL_TOO_SMALL) do
      true
    end

    def has_constant?(:SIP_STATUS_INTERVAL_TOO_BRIEF) do
      true
    end

    def has_constant?(:SIP_STATUS_BAD_LOCATION_INFORMATION) do
      true
    end

    def has_constant?(:SIP_STATUS_BAD_ALERT_MESSAGE) do
      true
    end

    def has_constant?(:SIP_STATUS_USE_IDENTITY_HEADER) do
      true
    end

    def has_constant?(:SIP_STATUS_PROVIDE_REFERRER_IDENTITY) do
      true
    end

    def has_constant?(:SIP_STATUS_FLOW_FAILED) do
      true
    end

    def has_constant?(:SIP_STATUS_ANONYMITY_DISALLOWED) do
      true
    end

    def has_constant?(:SIP_STATUS_BAD_IDENTITY_INFO) do
      true
    end

    def has_constant?(:SIP_STATUS_UNSUPPORTED_CERTIFICATE) do
      true
    end

    def has_constant?(:SIP_STATUS_INVALID_IDENTITY_HEADER) do
      true
    end

    def has_constant?(:SIP_STATUS_FIRST_HOP_LACKS_OUTBOUND_SUPPORT) do
      true
    end

    def has_constant?(:SIP_STATUS_MAX_BREADTH_EXCEEDED) do
      true
    end

    def has_constant?(:SIP_STATUS_BAD_INFO_PACKAGE) do
      true
    end

    def has_constant?(:SIP_STATUS_CONSENT_NEEDED) do
      true
    end

    def has_constant?(:SIP_STATUS_TEMPORARILY_UNAVAILABLE) do
      true
    end

    def has_constant?(:SIP_STATUS_CALL_TRANSACTION_DOES_NOT_EXISTS) do
      true
    end

    def has_constant?(:SIP_STATUS_LOOP_DETECTED) do
      true
    end

    def has_constant?(:SIP_STATUS_TOO_MANY_HOPS) do
      true
    end

    def has_constant?(:SIP_STATUS_ADDRESS_INCOMPLETE) do
      true
    end

    def has_constant?(:SIP_STATUS_AMBIGUOUS) do
      true
    end

    def has_constant?(:SIP_STATUS_BUSY_HERE) do
      true
    end

    def has_constant?(:SIP_STATUS_REQUEST_TERMINATED) do
      true
    end

    def has_constant?(:SIP_STATUS_NOT_ACCEPTABLE_HERE) do
      true
    end

    def has_constant?(:SIP_STATUS_BAD_EVENT) do
      true
    end

    def has_constant?(:SIP_STATUS_REQUEST_PENDING) do
      true
    end

    def has_constant?(:SIP_STATUS_UNDECIPHERABLE) do
      true
    end

    def has_constant?(:SIP_STATUS_SECURITY_AGREEMENT_REQUIRED) do
      true
    end

    def has_constant?(:SIP_STATUS_INTERNAL_SERVER_ERROR) do
      true
    end

    def has_constant?(:SIP_STATUS_NOT_IMPLEMENTED) do
      true
    end

    def has_constant?(:SIP_STATUS_BAD_GATEWAY) do
      true
    end

    def has_constant?(:SIP_STATUS_SERVICE_UNAVAILABLE) do
      true
    end

    def has_constant?(:SIP_STATUS_GATEWAY_TIMEOUT) do
      true
    end

    def has_constant?(:SIP_STATUS_VERSION_NOT_SUPPORTED) do
      true
    end

    def has_constant?(:SIP_STATUS_MESSAGE_TOO_LARGE) do
      true
    end

    def has_constant?(:SIP_STATUS_GLOBAL_BUSY_EVERYWHERE) do
      true
    end

    def has_constant?(:SIP_STATUS_GLOBAL_DECLINE) do
      true
    end

    def has_constant?(:SIP_STATUS_GLOBAL_DOES_NOT_EXIST_ANYWHERE) do
      true
    end

    def has_constant?(:SIP_STATUS_GLOBAL_NOT_ACCEPTABLE) do
      true
    end

    def has_constant?(:SIP_STATUS_GLOBAL_UNWANTED) do
      true
    end

    def has_constant?(:SIP_STATUS_GLOBAL_REJECTED) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
