# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LiveKitProtocolEx.StartSession do
  @moduledoc false
  if function_exported?(Protox, :check_generator_version, 1) do
    Protox.check_generator_version(1)
  else
    raise "This code was generated with protox 2 but the runtime is using an older version of protox."
  end

  @type t :: %__MODULE__{
          use_single_peer_connection: boolean(),
          sync_state: LiveKitProtocolEx.SyncState.t() | nil,
          publisher_offer: LiveKitProtocolEx.SessionDescription.t() | nil,
          add_track_requests: [LiveKitProtocolEx.AddTrackRequest.t()],
          create_room: LiveKitProtocolEx.CreateRoomRequest.t() | nil,
          disable_ice_lite: boolean(),
          reconnect_reason: atom(),
          participant_id: String.t(),
          adaptive_stream: boolean(),
          grants_json: String.t(),
          name: String.t(),
          recorder: boolean(),
          client: LiveKitProtocolEx.ClientInfo.t() | nil,
          hidden: boolean(),
          auto_subscribe: boolean(),
          reconnect: boolean(),
          connection_id: String.t(),
          identity: String.t(),
          room_name: String.t(),
          subscriber_allow_pause: boolean() | nil,
          __uf__: [{non_neg_integer(), Protox.Types.tag(), binary()}]
        }
  defstruct use_single_peer_connection: false,
            sync_state: nil,
            publisher_offer: nil,
            add_track_requests: [],
            create_room: nil,
            disable_ice_lite: false,
            subscriber_allow_pause: nil,
            reconnect_reason: :RR_UNKNOWN,
            participant_id: "",
            adaptive_stream: false,
            grants_json: "",
            name: "",
            recorder: false,
            client: nil,
            hidden: false,
            auto_subscribe: false,
            reconnect: false,
            connection_id: "",
            identity: "",
            room_name: "",
            __uf__: []

  (
    (
      @spec encode(t()) :: {:ok, iodata(), non_neg_integer()} | {:error, any()}
      def encode(msg) do
        msg |> encode!() |> Tuple.insert_at(0, :ok)
      rescue
        e in [Protox.EncodingError, Protox.RequiredFieldsError] -> {:error, e}
      end

      @spec encode!(t()) :: {iodata(), non_neg_integer()} | no_return()
      def encode!(msg) do
        {_acc = [], _acc_size = 0}
        |> encode_subscriber_allow_pause(msg)
        |> encode_use_single_peer_connection(msg)
        |> encode_sync_state(msg)
        |> encode_publisher_offer(msg)
        |> encode_add_track_requests(msg)
        |> encode_create_room(msg)
        |> encode_disable_ice_lite(msg)
        |> encode_reconnect_reason(msg)
        |> encode_participant_id(msg)
        |> encode_adaptive_stream(msg)
        |> encode_grants_json(msg)
        |> encode_name(msg)
        |> encode_recorder(msg)
        |> encode_client(msg)
        |> encode_hidden(msg)
        |> encode_auto_subscribe(msg)
        |> encode_reconnect(msg)
        |> encode_connection_id(msg)
        |> encode_identity(msg)
        |> encode_room_name(msg)
        |> encode_unknown_fields(msg)
      end
    )

    defp encode_use_single_peer_connection({acc, acc_size}, msg) do
      if msg.use_single_peer_connection == false do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} =
          Protox.Encode.encode_bool(msg.use_single_peer_connection)

        {["\xC0\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:use_single_peer_connection, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_sync_state({acc, acc_size}, msg) do
      if msg.sync_state == nil do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_message(msg.sync_state)
        {["\xBA\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:sync_state, "invalid field value"), __STACKTRACE__
    end

    defp encode_publisher_offer({acc, acc_size}, msg) do
      if msg.publisher_offer == nil do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_message(msg.publisher_offer)
        {["\xB2\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:publisher_offer, "invalid field value"), __STACKTRACE__
    end

    defp encode_add_track_requests({acc, acc_size}, msg) do
      case msg.add_track_requests do
        [] ->
          {acc, acc_size}

        values ->
          {value_bytes, value_size} =
            (
              {value_bytes, value_size} =
                Enum.reduce(values, {_local_acc = [], _local_acc_size = 0}, fn value,
                                                                               {local_acc,
                                                                                local_acc_size} ->
                  {value_bytes, value_bytes_size} = Protox.Encode.encode_message(value)
                  {[value_bytes, "\xAA\x01" | local_acc], local_acc_size + 2 + value_bytes_size}
                end)

              {Enum.reverse(value_bytes), value_size}
            )

          {[value_bytes | acc], acc_size + value_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:add_track_requests, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_create_room({acc, acc_size}, msg) do
      if msg.create_room == nil do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_message(msg.create_room)
        {["\xA2\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:create_room, "invalid field value"), __STACKTRACE__
    end

    defp encode_disable_ice_lite({acc, acc_size}, msg) do
      if msg.disable_ice_lite == false do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_bool(msg.disable_ice_lite)
        {["\x98\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:disable_ice_lite, "invalid field value"), __STACKTRACE__
    end

    defp encode_subscriber_allow_pause({acc, acc_size}, msg) do
      case msg.subscriber_allow_pause do
        nil ->
          {acc, acc_size}

        child_field_value ->
          {value_bytes, value_bytes_size} = Protox.Encode.encode_bool(child_field_value)
          {["\x90\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:subscriber_allow_pause, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_reconnect_reason({acc, acc_size}, msg) do
      if msg.reconnect_reason == :RR_UNKNOWN do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} =
          msg.reconnect_reason
          |> LiveKitProtocolEx.ReconnectReason.encode()
          |> Protox.Encode.encode_enum()

        {["\x88\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:reconnect_reason, "invalid field value"), __STACKTRACE__
    end

    defp encode_participant_id({acc, acc_size}, msg) do
      if msg.participant_id == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.participant_id)
        {["\x82\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:participant_id, "invalid field value"), __STACKTRACE__
    end

    defp encode_adaptive_stream({acc, acc_size}, msg) do
      if msg.adaptive_stream == false do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_bool(msg.adaptive_stream)
        {["x", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:adaptive_stream, "invalid field value"), __STACKTRACE__
    end

    defp encode_grants_json({acc, acc_size}, msg) do
      if msg.grants_json == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.grants_json)
        {["r", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:grants_json, "invalid field value"), __STACKTRACE__
    end

    defp encode_name({acc, acc_size}, msg) do
      if msg.name == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.name)
        {["j", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:name, "invalid field value"), __STACKTRACE__
    end

    defp encode_recorder({acc, acc_size}, msg) do
      if msg.recorder == false do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_bool(msg.recorder)
        {["`", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:recorder, "invalid field value"), __STACKTRACE__
    end

    defp encode_client({acc, acc_size}, msg) do
      if msg.client == nil do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_message(msg.client)
        {["Z", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:client, "invalid field value"), __STACKTRACE__
    end

    defp encode_hidden({acc, acc_size}, msg) do
      if msg.hidden == false do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_bool(msg.hidden)
        {["P", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:hidden, "invalid field value"), __STACKTRACE__
    end

    defp encode_auto_subscribe({acc, acc_size}, msg) do
      if msg.auto_subscribe == false do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_bool(msg.auto_subscribe)
        {["H", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:auto_subscribe, "invalid field value"), __STACKTRACE__
    end

    defp encode_reconnect({acc, acc_size}, msg) do
      if msg.reconnect == false do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_bool(msg.reconnect)
        {[" ", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:reconnect, "invalid field value"), __STACKTRACE__
    end

    defp encode_connection_id({acc, acc_size}, msg) do
      if msg.connection_id == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.connection_id)
        {["\x1A", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:connection_id, "invalid field value"), __STACKTRACE__
    end

    defp encode_identity({acc, acc_size}, msg) do
      if msg.identity == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.identity)
        {["\x12", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:identity, "invalid field value"), __STACKTRACE__
    end

    defp encode_room_name({acc, acc_size}, msg) do
      if msg.room_name == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.room_name)
        {["\n", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:room_name, "invalid field value"), __STACKTRACE__
    end

    defp encode_unknown_fields({acc, acc_size}, msg) do
      Enum.reduce(msg.__uf__, {acc, acc_size}, fn {tag, wire_type, bytes}, {acc, acc_size} ->
        case wire_type do
          0 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :int32)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}

          1 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :double)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}

          2 ->
            {len_bytes, len_size} = bytes |> byte_size() |> Protox.Varint.encode()
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :packed)

            {[acc, <<key_bytes::binary, len_bytes::binary, bytes::binary>>],
             acc_size + key_size + len_size + byte_size(bytes)}

          5 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :float)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}
        end
      end)
    end
  )

  (
    (
      @spec decode(binary()) :: {:ok, t()} | {:error, any()}
      def decode(bytes) do
        {:ok, decode!(bytes)}
      rescue
        e in [Protox.DecodingError, Protox.IllegalTagError, Protox.RequiredFieldsError] ->
          {:error, e}
      end

      (
        @spec decode!(binary()) :: t() | no_return()
        def decode!(bytes) do
          parse_key_value(bytes, struct(LiveKitProtocolEx.StartSession))
        end
      )
    )

    (
      @spec parse_key_value(binary(), struct()) :: struct()
      defp parse_key_value(<<>>, msg) do
        msg
      end

      defp parse_key_value(bytes, msg) do
        {field, rest} =
          case bytes do
            <<_::5, 3::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 3")

            <<_::5, 4::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 4")

            <<_::5, 6::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 6")

            <<_::5, 7::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 7")

            <<0::5, _::3, _rest::binary>> ->
              raise %Protox.IllegalTagError{}

            <<24::5, _wire_type::3, "\x01", bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_bool(bytes)
              {[use_single_peer_connection: value], rest}

            <<23::5, _wire_type::3, "\x01", bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 sync_state:
                   Protox.MergeMessage.merge(
                     msg.sync_state,
                     LiveKitProtocolEx.SyncState.decode!(delimited)
                   )
               ], rest}

            <<22::5, _wire_type::3, "\x01", bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 publisher_offer:
                   Protox.MergeMessage.merge(
                     msg.publisher_offer,
                     LiveKitProtocolEx.SessionDescription.decode!(delimited)
                   )
               ], rest}

            <<21::5, _wire_type::3, "\x01", bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 add_track_requests:
                   msg.add_track_requests ++
                     [LiveKitProtocolEx.AddTrackRequest.decode!(delimited)]
               ], rest}

            <<20::5, _wire_type::3, "\x01", bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 create_room:
                   Protox.MergeMessage.merge(
                     msg.create_room,
                     LiveKitProtocolEx.CreateRoomRequest.decode!(delimited)
                   )
               ], rest}

            <<19::5, _wire_type::3, "\x01", bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_bool(bytes)
              {[disable_ice_lite: value], rest}

            <<18::5, _wire_type::3, "\x01", bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_bool(bytes)
              {[subscriber_allow_pause: value], rest}

            <<17::5, _wire_type::3, "\x01", bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_enum(bytes, LiveKitProtocolEx.ReconnectReason)
              {[reconnect_reason: value], rest}

            <<16::5, _wire_type::3, "\x01", bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[participant_id: Protox.Decode.validate_string!(delimited)], rest}

            <<15::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_bool(bytes)
              {[adaptive_stream: value], rest}

            <<14::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[grants_json: Protox.Decode.validate_string!(delimited)], rest}

            <<13::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[name: Protox.Decode.validate_string!(delimited)], rest}

            <<12::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_bool(bytes)
              {[recorder: value], rest}

            <<11::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 client:
                   Protox.MergeMessage.merge(
                     msg.client,
                     LiveKitProtocolEx.ClientInfo.decode!(delimited)
                   )
               ], rest}

            <<10::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_bool(bytes)
              {[hidden: value], rest}

            <<9::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_bool(bytes)
              {[auto_subscribe: value], rest}

            <<4::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_bool(bytes)
              {[reconnect: value], rest}

            <<3::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[connection_id: Protox.Decode.validate_string!(delimited)], rest}

            <<2::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[identity: Protox.Decode.validate_string!(delimited)], rest}

            <<1::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[room_name: Protox.Decode.validate_string!(delimited)], rest}

            <<bytes::binary>> ->
              {tag, wire_type, rest} = Protox.Decode.parse_key(bytes)
              {value, rest} = Protox.Decode.parse_unknown(tag, wire_type, rest)
              {[__uf__: msg.__uf__ ++ [value]], rest}
          end

        msg_updated = struct(msg, field)
        parse_key_value(rest, msg_updated)
      end
    )
  )

  (
    @spec unknown_fields(struct()) :: [{non_neg_integer(), Protox.Types.tag(), binary()}]
    def unknown_fields(msg) do
      msg.__uf__
    end

    @spec unknown_fields_name() :: :__uf__
    def unknown_fields_name() do
      :__uf__
    end

    @spec clear_unknown_fields(struct) :: struct
    def clear_unknown_fields(msg) do
      struct!(msg, __uf__: [])
    end
  )

  (
    @spec default(atom()) ::
            {:ok, boolean() | integer() | String.t() | float()}
            | {:error, :no_such_field | :no_default_value}
    def default(:use_single_peer_connection) do
      {:ok, false}
    end

    def default(:sync_state) do
      {:ok, nil}
    end

    def default(:publisher_offer) do
      {:ok, nil}
    end

    def default(:add_track_requests) do
      {:error, :no_default_value}
    end

    def default(:create_room) do
      {:ok, nil}
    end

    def default(:disable_ice_lite) do
      {:ok, false}
    end

    def default(:subscriber_allow_pause) do
      {:error, :no_default_value}
    end

    def default(:reconnect_reason) do
      {:ok, :RR_UNKNOWN}
    end

    def default(:participant_id) do
      {:ok, ""}
    end

    def default(:adaptive_stream) do
      {:ok, false}
    end

    def default(:grants_json) do
      {:ok, ""}
    end

    def default(:name) do
      {:ok, ""}
    end

    def default(:recorder) do
      {:ok, false}
    end

    def default(:client) do
      {:ok, nil}
    end

    def default(:hidden) do
      {:ok, false}
    end

    def default(:auto_subscribe) do
      {:ok, false}
    end

    def default(:reconnect) do
      {:ok, false}
    end

    def default(:connection_id) do
      {:ok, ""}
    end

    def default(:identity) do
      {:ok, ""}
    end

    def default(:room_name) do
      {:ok, ""}
    end

    def default(_) do
      {:error, :no_such_field}
    end
  )

  @spec schema() :: Protox.MessageSchema.t()
  def schema() do
    %{
      __struct__: Protox.MessageSchema,
      fields: %{
        adaptive_stream: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: false},
          label: :optional,
          name: :adaptive_stream,
          tag: 15,
          type: :bool
        },
        add_track_requests: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: :unpacked,
          label: :repeated,
          name: :add_track_requests,
          tag: 21,
          type: {:message, LiveKitProtocolEx.AddTrackRequest}
        },
        auto_subscribe: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: false},
          label: :optional,
          name: :auto_subscribe,
          tag: 9,
          type: :bool
        },
        client: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: nil},
          label: :optional,
          name: :client,
          tag: 11,
          type: {:message, LiveKitProtocolEx.ClientInfo}
        },
        connection_id: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :connection_id,
          tag: 3,
          type: :string
        },
        create_room: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: nil},
          label: :optional,
          name: :create_room,
          tag: 20,
          type: {:message, LiveKitProtocolEx.CreateRoomRequest}
        },
        disable_ice_lite: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: false},
          label: :optional,
          name: :disable_ice_lite,
          tag: 19,
          type: :bool
        },
        grants_json: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :grants_json,
          tag: 14,
          type: :string
        },
        hidden: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: false},
          label: :optional,
          name: :hidden,
          tag: 10,
          type: :bool
        },
        identity: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :identity,
          tag: 2,
          type: :string
        },
        name: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :name,
          tag: 13,
          type: :string
        },
        participant_id: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :participant_id,
          tag: 16,
          type: :string
        },
        publisher_offer: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: nil},
          label: :optional,
          name: :publisher_offer,
          tag: 22,
          type: {:message, LiveKitProtocolEx.SessionDescription}
        },
        reconnect: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: false},
          label: :optional,
          name: :reconnect,
          tag: 4,
          type: :bool
        },
        reconnect_reason: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: :RR_UNKNOWN},
          label: :optional,
          name: :reconnect_reason,
          tag: 17,
          type: {:enum, LiveKitProtocolEx.ReconnectReason}
        },
        recorder: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: false},
          label: :optional,
          name: :recorder,
          tag: 12,
          type: :bool
        },
        room_name: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :room_name,
          tag: 1,
          type: :string
        },
        subscriber_allow_pause: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.OneOf, parent: :_subscriber_allow_pause},
          label: :proto3_optional,
          name: :subscriber_allow_pause,
          tag: 18,
          type: :bool
        },
        sync_state: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: nil},
          label: :optional,
          name: :sync_state,
          tag: 23,
          type: {:message, LiveKitProtocolEx.SyncState}
        },
        use_single_peer_connection: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: false},
          label: :optional,
          name: :use_single_peer_connection,
          tag: 24,
          type: :bool
        }
      },
      file_options: %{
        cc_enable_arenas: nil,
        cc_generic_services: nil,
        csharp_namespace: "LiveKit.Proto",
        deprecated: nil,
        features: nil,
        go_package: "github.com/livekit/protocol/livekit",
        java_generate_equals_and_hash: nil,
        java_generic_services: nil,
        java_multiple_files: nil,
        java_outer_classname: nil,
        java_package: nil,
        java_string_check_utf8: nil,
        objc_class_prefix: nil,
        optimize_for: nil,
        php_class_prefix: nil,
        php_metadata_namespace: nil,
        php_namespace: nil,
        py_generic_services: nil,
        ruby_package: "LiveKit::Proto",
        swift_prefix: nil,
        uninterpreted_option: []
      },
      name: LiveKitProtocolEx.StartSession,
      syntax: :proto3
    }
  end
end
