# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LivekitProtocolEx.Rpc.EvaluateSIPDispatchRulesResponse do
  @moduledoc false
  if function_exported?(Protox, :check_generator_version, 1) do
    Protox.check_generator_version(1)
  else
    raise "This code was generated with protox 2 but the runtime is using an older version of protox."
  end

  @type t :: %__MODULE__{
          media_encryption: atom(),
          room_config: LivekitProtocolEx.RoomConfiguration.t() | nil,
          room_preset: String.t(),
          include_headers: atom(),
          attributes_to_headers: %{String.t() => String.t()},
          max_call_duration: Google.Protobuf.Duration.t() | nil,
          ringing_timeout: Google.Protobuf.Duration.t() | nil,
          enabled_features: [atom()],
          headers_to_attributes: %{String.t() => String.t()},
          headers: %{String.t() => String.t()},
          project_id: String.t(),
          participant_attributes: %{String.t() => String.t()},
          sip_dispatch_rule_id: String.t(),
          sip_trunk_id: String.t(),
          participant_metadata: String.t(),
          participant_name: String.t(),
          result: atom(),
          ws_url: String.t(),
          token: String.t(),
          request_pin: boolean(),
          participant_identity: String.t(),
          room_name: String.t(),
          __uf__: [{non_neg_integer(), Protox.Types.tag(), binary()}]
        }
  defstruct media_encryption: :SIP_MEDIA_ENCRYPT_DISABLE,
            room_config: nil,
            room_preset: "",
            include_headers: :SIP_NO_HEADERS,
            attributes_to_headers: %{},
            max_call_duration: nil,
            ringing_timeout: nil,
            enabled_features: [],
            headers_to_attributes: %{},
            headers: %{},
            project_id: "",
            participant_attributes: %{},
            sip_dispatch_rule_id: "",
            sip_trunk_id: "",
            participant_metadata: "",
            participant_name: "",
            result: :LEGACY_ACCEPT_OR_PIN,
            ws_url: "",
            token: "",
            request_pin: false,
            participant_identity: "",
            room_name: "",
            __uf__: []

  (
    (
      @spec encode(t()) :: {:ok, iodata(), non_neg_integer()} | {:error, any()}
      def encode(msg) do
        msg |> encode!() |> Tuple.insert_at(0, :ok)
      rescue
        e in [Protox.EncodingError, Protox.RequiredFieldsError] -> {:error, e}
      end

      @spec encode!(t()) :: {iodata(), non_neg_integer()} | no_return()
      def encode!(msg) do
        {_acc = [], _acc_size = 0}
        |> encode_media_encryption(msg)
        |> encode_room_config(msg)
        |> encode_room_preset(msg)
        |> encode_include_headers(msg)
        |> encode_attributes_to_headers(msg)
        |> encode_max_call_duration(msg)
        |> encode_ringing_timeout(msg)
        |> encode_enabled_features(msg)
        |> encode_headers_to_attributes(msg)
        |> encode_headers(msg)
        |> encode_project_id(msg)
        |> encode_participant_attributes(msg)
        |> encode_sip_dispatch_rule_id(msg)
        |> encode_sip_trunk_id(msg)
        |> encode_participant_metadata(msg)
        |> encode_participant_name(msg)
        |> encode_result(msg)
        |> encode_ws_url(msg)
        |> encode_token(msg)
        |> encode_request_pin(msg)
        |> encode_participant_identity(msg)
        |> encode_room_name(msg)
        |> encode_unknown_fields(msg)
      end
    )

    defp encode_media_encryption({acc, acc_size}, msg) do
      if msg.media_encryption == :SIP_MEDIA_ENCRYPT_DISABLE do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} =
          msg.media_encryption
          |> LivekitProtocolEx.SIPMediaEncryption.encode()
          |> Protox.Encode.encode_enum()

        {["\xB0\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:media_encryption, "invalid field value"), __STACKTRACE__
    end

    defp encode_room_config({acc, acc_size}, msg) do
      if msg.room_config == nil do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_message(msg.room_config)
        {["\xAA\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:room_config, "invalid field value"), __STACKTRACE__
    end

    defp encode_room_preset({acc, acc_size}, msg) do
      if msg.room_preset == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.room_preset)
        {["\xA2\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:room_preset, "invalid field value"), __STACKTRACE__
    end

    defp encode_include_headers({acc, acc_size}, msg) do
      if msg.include_headers == :SIP_NO_HEADERS do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} =
          msg.include_headers
          |> LivekitProtocolEx.SIPHeaderOptions.encode()
          |> Protox.Encode.encode_enum()

        {["\x98\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:include_headers, "invalid field value"), __STACKTRACE__
    end

    defp encode_attributes_to_headers({acc, acc_size}, msg) do
      map = Map.fetch!(msg, :attributes_to_headers)

      if map_size(map) == 0 do
        {acc, acc_size}
      else
        Enum.reduce(map, {acc, acc_size}, fn {k, v}, {acc, acc_size} ->
          {k_value_bytes, k_value_len} = Protox.Encode.encode_string(k)
          {v_value_bytes, v_value_len} = Protox.Encode.encode_string(v)
          len = 2 + k_value_len + v_value_len
          {len_varint, len_varint_size} = Protox.Varint.encode(len)

          acc = [
            <<"\x92\x01", len_varint::binary, "\n">>,
            k_value_bytes,
            "\x12",
            v_value_bytes | acc
          ]

          {acc, acc_size + 4 + k_value_len + v_value_len + len_varint_size}
        end)
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:attributes_to_headers, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_max_call_duration({acc, acc_size}, msg) do
      if msg.max_call_duration == nil do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_message(msg.max_call_duration)
        {["\x8A\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:max_call_duration, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_ringing_timeout({acc, acc_size}, msg) do
      if msg.ringing_timeout == nil do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_message(msg.ringing_timeout)
        {["\x82\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:ringing_timeout, "invalid field value"), __STACKTRACE__
    end

    defp encode_enabled_features({acc, acc_size}, msg) do
      case msg.enabled_features do
        [] ->
          {acc, acc_size}

        values ->
          {packed_bytes, packed_size} =
            (
              {value_bytes, value_size} =
                Enum.reduce(values, {_local_acc = [], _local_acc_size = 0}, fn value,
                                                                               {local_acc,
                                                                                local_acc_size} ->
                  {value_bytes, value_bytes_size} =
                    value |> LivekitProtocolEx.SIPFeature.encode() |> Protox.Encode.encode_enum()

                  {[value_bytes | local_acc], local_acc_size + value_bytes_size}
                end)

              {value_size_bytes, value_size_size} = Protox.Varint.encode(value_size)
              {[value_size_bytes, Enum.reverse(value_bytes)], value_size + value_size_size}
            )

          {["z", packed_bytes | acc], acc_size + 1 + packed_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:enabled_features, "invalid field value"), __STACKTRACE__
    end

    defp encode_headers_to_attributes({acc, acc_size}, msg) do
      map = Map.fetch!(msg, :headers_to_attributes)

      if map_size(map) == 0 do
        {acc, acc_size}
      else
        Enum.reduce(map, {acc, acc_size}, fn {k, v}, {acc, acc_size} ->
          {k_value_bytes, k_value_len} = Protox.Encode.encode_string(k)
          {v_value_bytes, v_value_len} = Protox.Encode.encode_string(v)
          len = 2 + k_value_len + v_value_len
          {len_varint, len_varint_size} = Protox.Varint.encode(len)
          acc = [<<"r", len_varint::binary, "\n">>, k_value_bytes, "\x12", v_value_bytes | acc]
          {acc, acc_size + 3 + k_value_len + v_value_len + len_varint_size}
        end)
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:headers_to_attributes, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_headers({acc, acc_size}, msg) do
      map = Map.fetch!(msg, :headers)

      if map_size(map) == 0 do
        {acc, acc_size}
      else
        Enum.reduce(map, {acc, acc_size}, fn {k, v}, {acc, acc_size} ->
          {k_value_bytes, k_value_len} = Protox.Encode.encode_string(k)
          {v_value_bytes, v_value_len} = Protox.Encode.encode_string(v)
          len = 2 + k_value_len + v_value_len
          {len_varint, len_varint_size} = Protox.Varint.encode(len)
          acc = [<<"j", len_varint::binary, "\n">>, k_value_bytes, "\x12", v_value_bytes | acc]
          {acc, acc_size + 3 + k_value_len + v_value_len + len_varint_size}
        end)
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:headers, "invalid field value"), __STACKTRACE__
    end

    defp encode_project_id({acc, acc_size}, msg) do
      if msg.project_id == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.project_id)
        {["b", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:project_id, "invalid field value"), __STACKTRACE__
    end

    defp encode_participant_attributes({acc, acc_size}, msg) do
      map = Map.fetch!(msg, :participant_attributes)

      if map_size(map) == 0 do
        {acc, acc_size}
      else
        Enum.reduce(map, {acc, acc_size}, fn {k, v}, {acc, acc_size} ->
          {k_value_bytes, k_value_len} = Protox.Encode.encode_string(k)
          {v_value_bytes, v_value_len} = Protox.Encode.encode_string(v)
          len = 2 + k_value_len + v_value_len
          {len_varint, len_varint_size} = Protox.Varint.encode(len)
          acc = [<<"Z", len_varint::binary, "\n">>, k_value_bytes, "\x12", v_value_bytes | acc]
          {acc, acc_size + 3 + k_value_len + v_value_len + len_varint_size}
        end)
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:participant_attributes, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_sip_dispatch_rule_id({acc, acc_size}, msg) do
      if msg.sip_dispatch_rule_id == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.sip_dispatch_rule_id)
        {["R", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:sip_dispatch_rule_id, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_sip_trunk_id({acc, acc_size}, msg) do
      if msg.sip_trunk_id == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.sip_trunk_id)
        {["J", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:sip_trunk_id, "invalid field value"), __STACKTRACE__
    end

    defp encode_participant_metadata({acc, acc_size}, msg) do
      if msg.participant_metadata == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.participant_metadata)
        {["B", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:participant_metadata, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_participant_name({acc, acc_size}, msg) do
      if msg.participant_name == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.participant_name)
        {[":", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:participant_name, "invalid field value"), __STACKTRACE__
    end

    defp encode_result({acc, acc_size}, msg) do
      if msg.result == :LEGACY_ACCEPT_OR_PIN do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} =
          msg.result
          |> LivekitProtocolEx.Rpc.SIPDispatchResult.encode()
          |> Protox.Encode.encode_enum()

        {["0", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:result, "invalid field value"), __STACKTRACE__
    end

    defp encode_ws_url({acc, acc_size}, msg) do
      if msg.ws_url == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.ws_url)
        {["*", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:ws_url, "invalid field value"), __STACKTRACE__
    end

    defp encode_token({acc, acc_size}, msg) do
      if msg.token == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.token)
        {["\"", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:token, "invalid field value"), __STACKTRACE__
    end

    defp encode_request_pin({acc, acc_size}, msg) do
      if msg.request_pin == false do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_bool(msg.request_pin)
        {["\x18", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:request_pin, "invalid field value"), __STACKTRACE__
    end

    defp encode_participant_identity({acc, acc_size}, msg) do
      if msg.participant_identity == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.participant_identity)
        {["\x12", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:participant_identity, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_room_name({acc, acc_size}, msg) do
      if msg.room_name == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.room_name)
        {["\n", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:room_name, "invalid field value"), __STACKTRACE__
    end

    defp encode_unknown_fields({acc, acc_size}, msg) do
      Enum.reduce(msg.__uf__, {acc, acc_size}, fn {tag, wire_type, bytes}, {acc, acc_size} ->
        case wire_type do
          0 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :int32)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}

          1 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :double)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}

          2 ->
            {len_bytes, len_size} = bytes |> byte_size() |> Protox.Varint.encode()
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :packed)

            {[acc, <<key_bytes::binary, len_bytes::binary, bytes::binary>>],
             acc_size + key_size + len_size + byte_size(bytes)}

          5 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :float)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}
        end
      end)
    end
  )

  (
    (
      @spec decode(binary()) :: {:ok, t()} | {:error, any()}
      def decode(bytes) do
        {:ok, decode!(bytes)}
      rescue
        e in [Protox.DecodingError, Protox.IllegalTagError, Protox.RequiredFieldsError] ->
          {:error, e}
      end

      (
        @spec decode!(binary()) :: t() | no_return()
        def decode!(bytes) do
          parse_key_value(bytes, struct(LivekitProtocolEx.Rpc.EvaluateSIPDispatchRulesResponse))
        end
      )
    )

    (
      @spec parse_key_value(binary(), struct()) :: struct()
      defp parse_key_value(<<>>, msg) do
        msg
      end

      defp parse_key_value(bytes, msg) do
        {field, rest} =
          case bytes do
            <<_::5, 3::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 3")

            <<_::5, 4::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 4")

            <<_::5, 6::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 6")

            <<_::5, 7::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 7")

            <<0::5, _::3, _rest::binary>> ->
              raise %Protox.IllegalTagError{}

            <<22::5, _wire_type::3, "\x01", bytes::binary>> ->
              {value, rest} =
                Protox.Decode.parse_enum(bytes, LivekitProtocolEx.SIPMediaEncryption)

              {[media_encryption: value], rest}

            <<21::5, _wire_type::3, "\x01", bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 room_config:
                   Protox.MergeMessage.merge(
                     msg.room_config,
                     LivekitProtocolEx.RoomConfiguration.decode!(delimited)
                   )
               ], rest}

            <<20::5, _wire_type::3, "\x01", bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[room_preset: Protox.Decode.validate_string!(delimited)], rest}

            <<19::5, _wire_type::3, "\x01", bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_enum(bytes, LivekitProtocolEx.SIPHeaderOptions)
              {[include_headers: value], rest}

            <<18::5, _wire_type::3, "\x01", bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 (
                   {entry_key, entry_value} =
                     (
                       {map_key, map_value} = parse_string_string({:unset, :unset}, delimited)

                       map_key =
                         case map_key do
                           :unset -> Protox.Default.default(:string)
                           _ -> map_key
                         end

                       map_value =
                         case map_value do
                           :unset -> Protox.Default.default(:string)
                           _ -> map_value
                         end

                       {map_key, map_value}
                     )

                   {:attributes_to_headers,
                    Map.put(msg.attributes_to_headers, entry_key, entry_value)}
                 )
               ], rest}

            <<17::5, _wire_type::3, "\x01", bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 max_call_duration:
                   Protox.MergeMessage.merge(
                     msg.max_call_duration,
                     Google.Protobuf.Duration.decode!(delimited)
                   )
               ], rest}

            <<16::5, _wire_type::3, "\x01", bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 ringing_timeout:
                   Protox.MergeMessage.merge(
                     msg.ringing_timeout,
                     Google.Protobuf.Duration.decode!(delimited)
                   )
               ], rest}

            <<"z", bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 enabled_features:
                   msg.enabled_features ++
                     Protox.Decode.parse_repeated_enum(
                       [],
                       delimited,
                       LivekitProtocolEx.SIPFeature
                     )
               ], rest}

            <<15::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_enum(bytes, LivekitProtocolEx.SIPFeature)
              {[enabled_features: msg.enabled_features ++ [value]], rest}

            <<14::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 (
                   {entry_key, entry_value} =
                     (
                       {map_key, map_value} = parse_string_string({:unset, :unset}, delimited)

                       map_key =
                         case map_key do
                           :unset -> Protox.Default.default(:string)
                           _ -> map_key
                         end

                       map_value =
                         case map_value do
                           :unset -> Protox.Default.default(:string)
                           _ -> map_value
                         end

                       {map_key, map_value}
                     )

                   {:headers_to_attributes,
                    Map.put(msg.headers_to_attributes, entry_key, entry_value)}
                 )
               ], rest}

            <<13::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 (
                   {entry_key, entry_value} =
                     (
                       {map_key, map_value} = parse_string_string({:unset, :unset}, delimited)

                       map_key =
                         case map_key do
                           :unset -> Protox.Default.default(:string)
                           _ -> map_key
                         end

                       map_value =
                         case map_value do
                           :unset -> Protox.Default.default(:string)
                           _ -> map_value
                         end

                       {map_key, map_value}
                     )

                   {:headers, Map.put(msg.headers, entry_key, entry_value)}
                 )
               ], rest}

            <<12::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[project_id: Protox.Decode.validate_string!(delimited)], rest}

            <<11::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 (
                   {entry_key, entry_value} =
                     (
                       {map_key, map_value} = parse_string_string({:unset, :unset}, delimited)

                       map_key =
                         case map_key do
                           :unset -> Protox.Default.default(:string)
                           _ -> map_key
                         end

                       map_value =
                         case map_value do
                           :unset -> Protox.Default.default(:string)
                           _ -> map_value
                         end

                       {map_key, map_value}
                     )

                   {:participant_attributes,
                    Map.put(msg.participant_attributes, entry_key, entry_value)}
                 )
               ], rest}

            <<10::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[sip_dispatch_rule_id: Protox.Decode.validate_string!(delimited)], rest}

            <<9::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[sip_trunk_id: Protox.Decode.validate_string!(delimited)], rest}

            <<8::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[participant_metadata: Protox.Decode.validate_string!(delimited)], rest}

            <<7::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[participant_name: Protox.Decode.validate_string!(delimited)], rest}

            <<6::5, _wire_type::3, bytes::binary>> ->
              {value, rest} =
                Protox.Decode.parse_enum(bytes, LivekitProtocolEx.Rpc.SIPDispatchResult)

              {[result: value], rest}

            <<5::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[ws_url: Protox.Decode.validate_string!(delimited)], rest}

            <<4::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[token: Protox.Decode.validate_string!(delimited)], rest}

            <<3::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_bool(bytes)
              {[request_pin: value], rest}

            <<2::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[participant_identity: Protox.Decode.validate_string!(delimited)], rest}

            <<1::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[room_name: Protox.Decode.validate_string!(delimited)], rest}

            <<bytes::binary>> ->
              {tag, wire_type, rest} = Protox.Decode.parse_key(bytes)
              {value, rest} = Protox.Decode.parse_unknown(tag, wire_type, rest)
              {[__uf__: msg.__uf__ ++ [value]], rest}
          end

        msg_updated = struct(msg, field)
        parse_key_value(rest, msg_updated)
      end
    )

    (
      defp parse_string_string(map_entry, <<>>) do
        map_entry
      end

      defp parse_string_string({entry_key, entry_value}, bytes) do
        {map_entry, rest} =
          case Protox.Decode.parse_key(bytes) do
            {1, _, rest} ->
              {res, rest} =
                (
                  {len, new_rest} = Protox.Varint.decode(rest)
                  {delimited, new_rest} = Protox.Decode.parse_delimited(new_rest, len)
                  {Protox.Decode.validate_string!(delimited), new_rest}
                )

              {{res, entry_value}, rest}

            {2, _, rest} ->
              {res, rest} =
                (
                  {len, new_rest} = Protox.Varint.decode(rest)
                  {delimited, new_rest} = Protox.Decode.parse_delimited(new_rest, len)
                  {Protox.Decode.validate_string!(delimited), new_rest}
                )

              {{entry_key, res}, rest}

            {tag, wire_type, rest} ->
              {_, rest} = Protox.Decode.parse_unknown(tag, wire_type, rest)
              {{entry_key, entry_value}, rest}
          end

        parse_string_string(map_entry, rest)
      end
    )
  )

  (
    @spec unknown_fields(struct()) :: [{non_neg_integer(), Protox.Types.tag(), binary()}]
    def unknown_fields(msg) do
      msg.__uf__
    end

    @spec unknown_fields_name() :: :__uf__
    def unknown_fields_name() do
      :__uf__
    end

    @spec clear_unknown_fields(struct) :: struct
    def clear_unknown_fields(msg) do
      struct!(msg, __uf__: [])
    end
  )

  (
    @spec default(atom()) ::
            {:ok, boolean() | integer() | String.t() | float()}
            | {:error, :no_such_field | :no_default_value}
    def default(:media_encryption) do
      {:ok, :SIP_MEDIA_ENCRYPT_DISABLE}
    end

    def default(:room_config) do
      {:ok, nil}
    end

    def default(:room_preset) do
      {:ok, ""}
    end

    def default(:include_headers) do
      {:ok, :SIP_NO_HEADERS}
    end

    def default(:attributes_to_headers) do
      {:error, :no_default_value}
    end

    def default(:max_call_duration) do
      {:ok, nil}
    end

    def default(:ringing_timeout) do
      {:ok, nil}
    end

    def default(:enabled_features) do
      {:error, :no_default_value}
    end

    def default(:headers_to_attributes) do
      {:error, :no_default_value}
    end

    def default(:headers) do
      {:error, :no_default_value}
    end

    def default(:project_id) do
      {:ok, ""}
    end

    def default(:participant_attributes) do
      {:error, :no_default_value}
    end

    def default(:sip_dispatch_rule_id) do
      {:ok, ""}
    end

    def default(:sip_trunk_id) do
      {:ok, ""}
    end

    def default(:participant_metadata) do
      {:ok, ""}
    end

    def default(:participant_name) do
      {:ok, ""}
    end

    def default(:result) do
      {:ok, :LEGACY_ACCEPT_OR_PIN}
    end

    def default(:ws_url) do
      {:ok, ""}
    end

    def default(:token) do
      {:ok, ""}
    end

    def default(:request_pin) do
      {:ok, false}
    end

    def default(:participant_identity) do
      {:ok, ""}
    end

    def default(:room_name) do
      {:ok, ""}
    end

    def default(_) do
      {:error, :no_such_field}
    end
  )

  @spec schema() :: Protox.MessageSchema.t()
  def schema() do
    %{
      __struct__: Protox.MessageSchema,
      fields: %{
        attributes_to_headers: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: :map,
          label: nil,
          name: :attributes_to_headers,
          tag: 18,
          type: {:string, :string}
        },
        enabled_features: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: :packed,
          label: :repeated,
          name: :enabled_features,
          tag: 15,
          type: {:enum, LivekitProtocolEx.SIPFeature}
        },
        headers: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: :map,
          label: nil,
          name: :headers,
          tag: 13,
          type: {:string, :string}
        },
        headers_to_attributes: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: :map,
          label: nil,
          name: :headers_to_attributes,
          tag: 14,
          type: {:string, :string}
        },
        include_headers: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: :SIP_NO_HEADERS},
          label: :optional,
          name: :include_headers,
          tag: 19,
          type: {:enum, LivekitProtocolEx.SIPHeaderOptions}
        },
        max_call_duration: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: nil},
          label: :optional,
          name: :max_call_duration,
          tag: 17,
          type: {:message, Google.Protobuf.Duration}
        },
        media_encryption: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: :SIP_MEDIA_ENCRYPT_DISABLE},
          label: :optional,
          name: :media_encryption,
          tag: 22,
          type: {:enum, LivekitProtocolEx.SIPMediaEncryption}
        },
        participant_attributes: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: :map,
          label: nil,
          name: :participant_attributes,
          tag: 11,
          type: {:string, :string}
        },
        participant_identity: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :participant_identity,
          tag: 2,
          type: :string
        },
        participant_metadata: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :participant_metadata,
          tag: 8,
          type: :string
        },
        participant_name: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :participant_name,
          tag: 7,
          type: :string
        },
        project_id: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :project_id,
          tag: 12,
          type: :string
        },
        request_pin: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: false},
          label: :optional,
          name: :request_pin,
          tag: 3,
          type: :bool
        },
        result: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: :LEGACY_ACCEPT_OR_PIN},
          label: :optional,
          name: :result,
          tag: 6,
          type: {:enum, LivekitProtocolEx.Rpc.SIPDispatchResult}
        },
        ringing_timeout: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: nil},
          label: :optional,
          name: :ringing_timeout,
          tag: 16,
          type: {:message, Google.Protobuf.Duration}
        },
        room_config: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: nil},
          label: :optional,
          name: :room_config,
          tag: 21,
          type: {:message, LivekitProtocolEx.RoomConfiguration}
        },
        room_name: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :room_name,
          tag: 1,
          type: :string
        },
        room_preset: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :room_preset,
          tag: 20,
          type: :string
        },
        sip_dispatch_rule_id: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :sip_dispatch_rule_id,
          tag: 10,
          type: :string
        },
        sip_trunk_id: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :sip_trunk_id,
          tag: 9,
          type: :string
        },
        token: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :token,
          tag: 4,
          type: :string
        },
        ws_url: %{
          __struct__: Protox.Field,
          extender: nil,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :ws_url,
          tag: 5,
          type: :string
        }
      },
      file_options: %{
        cc_enable_arenas: nil,
        cc_generic_services: nil,
        csharp_namespace: nil,
        deprecated: nil,
        features: nil,
        go_package: "github.com/livekit/protocol/rpc",
        java_generate_equals_and_hash: nil,
        java_generic_services: nil,
        java_multiple_files: nil,
        java_outer_classname: nil,
        java_package: nil,
        java_string_check_utf8: nil,
        objc_class_prefix: nil,
        optimize_for: nil,
        php_class_prefix: nil,
        php_metadata_namespace: nil,
        php_namespace: nil,
        py_generic_services: nil,
        ruby_package: nil,
        swift_prefix: nil,
        uninterpreted_option: []
      },
      name: LivekitProtocolEx.Rpc.EvaluateSIPDispatchRulesResponse,
      syntax: :proto3
    }
  end
end
