# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule LiveKitProtocolEx.Rpc.SIPTrunkAuthenticationError do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :SIP_TRUNK_AUTH_ERROR_NONE
    def default() do
      :SIP_TRUNK_AUTH_ERROR_NONE
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:SIP_TRUNK_AUTH_ERROR_NONE) do
    0
  end

  def encode(:SIP_TRUNK_AUTH_ERROR_QUOTA_EXCEEDED) do
    1
  end

  def encode(:SIP_TRUNK_AUTH_ERROR_NO_TRUNK_FOUND) do
    2
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :SIP_TRUNK_AUTH_ERROR_NONE
  end

  def decode(1) do
    :SIP_TRUNK_AUTH_ERROR_QUOTA_EXCEEDED
  end

  def decode(2) do
    :SIP_TRUNK_AUTH_ERROR_NO_TRUNK_FOUND
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [
      {0, :SIP_TRUNK_AUTH_ERROR_NONE},
      {1, :SIP_TRUNK_AUTH_ERROR_QUOTA_EXCEEDED},
      {2, :SIP_TRUNK_AUTH_ERROR_NO_TRUNK_FOUND}
    ]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:SIP_TRUNK_AUTH_ERROR_NONE) do
      true
    end

    def has_constant?(:SIP_TRUNK_AUTH_ERROR_QUOTA_EXCEEDED) do
      true
    end

    def has_constant?(:SIP_TRUNK_AUTH_ERROR_NO_TRUNK_FOUND) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
